### ISSUE TITLE
Add Google Captcha v3 or other to feedback and contact forms

### ISSUE THREAD

**Issue by diana-lakatos** [Platform-OS/platformos-documentation#1012]

**Comment by Developer-DNM** [comment]
Thanks @diana-lakatos 

We might want to look at a different Captcha option too:
https://platformos.slack.com/archives/C02F8UTGF/p1586705091011600

https://www.hcaptcha.com/

**Comment by pavelloz** [comment]
It would be very cool to have hCaptcha and not Gcaptcha.

Not only recaptcha is planning to be paid, I have are privacy and performance concerns (hcaptcha's script is couple times smaller).

**Comment by diana-lakatos** [comment]
Captcha has been added.
