### ISSUE TITLE
Add topic: improved authorization scheme based on OAuth tokens

### ISSUE THREAD

**Issue by diana-lakatos** [Platform-OS/platformos-documentation#1015]
Document: Improved authorization scheme (for `pos-cli`) based on OAuth tokens - generated tokens will be scoped to one Instance. The old scheme is kept for backwards compatibility.

**Comment by pavelloz** [comment]
Actually, ill place it in release-notes/ scope

**Comment by pavelloz** [comment]
Blocked by
https://github.com/mdyd-dev/partner-portal/issues/1000

**Comment by diana-lakatos** [comment]
Part of pos-cli.
