### ISSUE TITLE
allcontributors bot

### ISSUE THREAD

**Issue by pavelloz** [Platform-OS/platformos-documentation#1018]
https://github.com/apps/allcontributors

This is how it works in practice:
https://github.com/rylandg/shrun/issues/1#issuecomment-613740153
https://github.com/rylandg/shrun/pull/14

This looks like a be better way of managing it than running some script locally.

**Comment by diana-lakatos** [comment]
As I can see this requires someone to add a comment whenever there is a new contributor. This might be difficult to keep track of with many contributors. Is there a way to automate this? 
Our current solution doesn't require any manual steps and keeps the contributor list always up-to-date and ordered.

**Comment by pavelloz** [comment]
Its not for contributors on the page, but in readme.md file which now require us to run scripts on local machines

**Comment by diana-lakatos** [comment]
Oh, I see! In that case, it's definitely an improvement. Thanks!

**Comment by pavelloz** [comment]
@all-contributors add @diana-lakatos for docs

**Comment by pavelloz** [comment]
Cool :)
