### ISSUE TITLE
Update use case for social cards 

### ISSUE THREAD

**Issue by pavelloz** [Platform-OS/platformos-documentation#1034]
Need to add structured data (added https://github.com/mdyd-dev/nearme-documentation/commit/1f736f9da86da98154abc1fb9d78ae70d5ed8140 )

**Comment by pavelloz** [comment]
Testing tool: https://search.google.com/structured-data/testing-tool/u/0/
Standard description: https://schema.org/

Good articles: 
https://developers.google.com/search/docs/guides/intro-structured-data
https://www.lullabot.com/articles/create-seo-juice-by-adding-json-ld-structured-data-to-drupal-8
https://neilpatel.com/blog/structured-data/

**Comment by Developer-DNM** [comment]
@pavelloz can you have @diana-lakatos add this as a Best practice article.

And we will update the pOS blog Module (in Module Marketplace) to comply too.

Cc @arturpawlak something the client team should be aware of when building sites.
