### ISSUE TITLE
Best practice: adding structured data

### ISSUE THREAD

**Issue by diana-lakatos** [Platform-OS/platformos-documentation#1035]
Describe what we did and why, include useful links:
#1032 
#1034

**Comment by pavelloz** [comment]
Isnt this just done?

https://documentation.platformos.com/use-cases/implementing-social-media-preview-cards

**Comment by diana-lakatos** [comment]
I thought this was a separate one because of this message: https://github.com/mdyd-dev/nearme-documentation/issues/1034#issuecomment-615889172 

If it's already done, let's close this ticket. Thank you!

**Comment by pavelloz** [comment]
Well, i dont have anything to add besides doing what i described in https://github.com/mdyd-dev/nearme-documentation/issues/1034#issue-602444361 ;)
