### ISSUE TITLE
User feedback: Angular 9

### ISSUE THREAD

**Issue by diana-lakatos** [Platform-OS/platformos-documentation#1047]
Message: i want  to use platformOS with Angular9, So i want tutorials for that can you help me

**Comment by Developer-DNM** [comment]
I think @maciej-webpassion is our resident Angular guru.

Decura.me was written in Angular

cc @diana-lakatos

**Comment by diana-lakatos** [comment]
We have this topic but it's not added in the navigation and search doesn't bring it up as a result when searching for Angular.
https://documentation.platformos.com/developer-guide/web-apps/connecting-angular-spa-platformos

@pavelloz Where do you suggest we should put it? In the DEVELOPMENT section, maybe?
Also, why doesn't it come up as a search result? 

![Screenshot 2020-04-27 at 7 54 20](https://user-images.githubusercontent.com/4191691/80338350-6882e900-885c-11ea-912e-00033bbad47e.jpg)

**Comment by diana-lakatos** [comment]
We discussed the following to dos:

- [ ] add example repo to tutorial
- [x] add link in navigation (this will fix search)

**Comment by diana-lakatos** [comment]
https://documentation.platformos.com/use-cases/connecting-angular-spa-platformos 

- [ ] add example repo to tutorial

**Comment by hosszukalman** [comment]
I just created a repository: https://github.com/mdyd-dev/angular-spa/tree/master
