### ISSUE TITLE
Add stale bot

### ISSUE THREAD

**Issue by pavelloz** [Platform-OS/platformos-documentation#1050]
We can automate tagging and closing issues that are inactive for X days.

https://github.com/apps/stale

**Comment by diana-lakatos** [comment]
There are different reasons for issues being inactive (e.g. we add ideas for articles that we want to write later), so I don't think we should automate closing issues. It could help if some automation would notify us of the issues being inactive for a given period of time and we could check them manually. What do you think?

**Comment by pavelloz** [comment]
We can configure it to close only those with a some label, or not touch issues with a certain label. It has configuration https://github.com/apps/stale

**Comment by diana-lakatos** [comment]
That could work! Let me please look into this soon to come up with a plan.
