### ISSUE TITLE
Review lighthouse article

### ISSUE THREAD

**Issue by pavelloz** [Platform-OS/platformos-documentation#1052]
https://github.com/mdyd-dev/nearme-documentation/commit/4fa897cda74872a8b5e31e05ed1a8cb2fcd9856c

By accident i pushed to master and not separate branch :)

**Comment by Developer-DNM** [comment]
https://www.youtube.com/watch?v=wCsO56kWwTc 

We don't make mistakes. We have happy accidents.

**Comment by diana-lakatos** [comment]
Reviewed and edited, thank you!
