### ISSUE TITLE
Adjust design of GraphQL API Reference

### ISSUE THREAD

**Issue by diana-lakatos** [Platform-OS/platformos-documentation#1061]
Make some minor adjustments to make the design of the [GraphQL API Reference](https://documentation.platformos.com/api-reference/graphql/rootquery.html) more consistent with the design of the documentation site. 
For example: change logo, change the fonts to the brand font, format the links and codes, use a very simple branded header.

Start only after #894 is done.

**Comment by GyongyGora** [comment]
Here is the new design. I kept the layout here too and changed the formatting of the elements only.
https://www.figma.com/file/jGVHdStunTaBLMWXINGZUK/pOS-docs-design-3?node-id=335%3A7

**Comment by pavelloz** [comment]
Done https://documentation.platformos.com/api-reference/graphql/rootquery.html
