### ISSUE TITLE
developer-guide/platformos-workflow/pos-cli

### ISSUE THREAD

**Issue by pavelloz** [Platform-OS/platformos-documentation#1063]
https://documentation.platformos.com/developer-guide/platformos-workflow/pos-cli

This page is outdated and will be outdated. pos-cli readme is outdated too.

We need one place to have pos-cli documentation and IMO it should be readme, since its also on npmjs and github. Ideally autogenerated, but that ship has sailed with our tech choice, so next best thing is to keep it one place, try to keep up, and link to it from other places.

**Comment by diana-lakatos** [comment]
We still need the pos-cli topic, but could keep only the parts that don't change (e.g. explanation on what the pos-cli is), and then link to the readme. 
We could also consider pulling the information from the readme file and displaying it on the documentation site (as it's markdown format), if possible.

**Comment by pavelloz** [comment]
https://github.com/mdyd-dev/nearme-documentation/issues/1108
