### ISSUE TITLE
Design - polishing

### ISSUE THREAD

**Issue by pavelloz** [Platform-OS/platformos-documentation#1069]
- [x] single release note page 
- [x] /api-reference -> h2 -> h3 to improve search results
- [x] contributors -> rewrite to tailwind
- [x] font weights on home
- [x] buttons paddings/size
- [x] feedback colors, icons, divider, width
- [ ] external link icon

**Comment by diana-lakatos** [comment]
Could you please add these to the polishing, too? If I can do any of them, please let me know how to (e.g. navigation fix), and I'll do them. Thank you! 

- [x] We had more topics in the Developer Guide/Development category, and they are now not displayed in the navigation on the left and I can't find them based on the link. These topics are missing:
Development Workflow
pos-cli
Effective Development Using the pos-cli 

- [x] The feedback / contribute to this page section doesn't exactly look like on the design. 

- [x] The active menu item is not shown in the left navigation (it should be blue). 

- [ ] The active top menu item doesn't have the little blue triangle above it. (This is not a big issue, as the active menu item is otherwise blue, so still visible.)

**Comment by GyongyGora** [comment]
It looks so nice! I only found some small things to do:
- [x] Graphics (line network and triangles in the hero, CTA, search bar, etc) are faded everywhere
- [ ] Please change the 'external link' icons in the footer and align them 
- [ ] Please add the next next to the Award logo in the footer
- [x] Buttons (Contact us, try now etc.) should be light blue and their hover state dark blue 
- [x] Hover shadow of cards: color: 343D4B opacity: 30%, blur:30, x:0, y:10
- [x] Divider line missing between 'Was this helpful' and 'Contribute...' in the feedback section
- [ ] Try now page (https://documentation.platformos.com/try-now) : here the cards and bg should look the same as on the home page. _I think, I'll create a design for this._

**Comment by GyongyGora** [comment]
Here is a simple design suggestion for the Try Now page: https://www.figma.com/file/jGVHdStunTaBLMWXINGZUK/pOS-docs-design-3?node-id=290%3A0

**Comment by diana-lakatos** [comment]
@GyongyGora @pavelloz 

> Please add the text next to the Award logo in the footer

I changed this text in Figma, I think it would be better to add it this way. 

Thanks!

**Comment by pavelloz** [comment]
>  Buttons (Contact us, try now etc.) should be light blue and their hover state dark blue

Lighthouse reports that as accessibility issue, so thats a no go.

**Comment by pavelloz** [comment]
>  Graphics (line network and triangles in the hero, CTA, search bar, etc) are faded everywhere

I did it because there is no way i will be able to position them so they never interfere with content. So now even in some obscure cases when they do interfere, its not making content unreadable. On mobile it is basically a must, especially in search bar.

**Comment by pavelloz** [comment]
> Please change the 'external link' icons in the footer and align them

Are you sure? It doesnt look like universal external link icon which is what most people are used to:

https://www.google.com/search?q=link+external+icon&oq=link+external+icon
https://www.flaticon.com/search?search-type=icons&word=external+link

**Comment by GyongyGora** [comment]
> > Please change the 'external link' icons in the footer and align them
> 
> Are you sure? It doesnt look like universal external link icon which is what most people are used to:
> 
> https://www.google.com/search?q=link+external+icon&oq=link+external+icon
> https://www.flaticon.com/search?search-type=icons&word=external+link

I know, but the old one is not from our icon pack. Please change all the UI icons and use our licensed 10.000+ icons. 

For the external links, then this might be good: https://www.figma.com/file/jTetwGJVh65MBrKh2KY0Jt/01-Interface-Essential?node-id=0%3A6055

**Comment by pavelloz** [comment]
Looks good, but export button doesnt show for me

**Comment by pavelloz** [comment]
Closing, most is done, rest will be continued within other cards
