### ISSUE TITLE
Update Liquid reference (include with)

### ISSUE THREAD

**Issue by diana-lakatos** [Platform-OS/platformos-documentation#1072]
User feedback: 
Feedback to: https://documentation.platformos.com/api-reference/liquid/include
Message: I'm not understanding the section here about "include with"  and the official liquid docs are thin on this topic as well.  One  problem is that the example given doesn't explain what is in the  product.liquid include file and what is not.  I'm also not sure what the  actual issues are that "with" is supposed to help get around.

**Comment by pavelloz** [comment]
<img width="713" alt="image" src="https://user-images.githubusercontent.com/546845/81312798-56d4e900-9087-11ea-8dd3-e9a5761b76ed.png">

If thats not clear, we need someone else who understands it to reword it.
