### ISSUE TITLE
After clicking on the "Contribute to this page "appears 404 Page Not Found

### ISSUE THREAD

**Issue by jnorbert** [Platform-OS/platformos-documentation#1074]
URL: https://documentation.platformos.com/api-reference/rest-api/

Steps to reproduce:
Click on the Contribute to this page icon

Actual result:
<img width="2554" alt="Screenshot 2020-05-05 at 21 46 04" src="https://user-images.githubusercontent.com/13810654/81109087-db095e00-8f19-11ea-877f-9a6941d748af.png">

**Comment by pavelloz** [comment]
Rest api is being removed
