### ISSUE TITLE
non-existent pages

### ISSUE THREAD

**Issue by jnorbert** [Platform-OS/platformos-documentation#1077]
URL: 
https://documentation.platformos.com/api-reference/graphql/authorizationpolicycollection.html
https://take.ms/FzBTG

https://documentation.platformos.com/api-reference/graphql/usercollection.html
https://take.ms/I068B

https://documentation.platformos.com/api-reference/graphql/graphquerycollection.html
https://take.ms/Sj78v

https://documentation.platformos.com/api-reference/graphql/user.html
https://take.ms/rSw3k

https://documentation.platformos.com/use-cases/connecting-angular-spa-platformos
https://take.ms/MkzgB

https://documentation.platformos.com/api-reference/graphql/attachmentpresigneduploadurl.html
https://take.ms/KtCHY

https://documentation.platformos.com/api-reference/graphql/rootmutation.html
https://take.ms/Hvf6V

https://documentation.platformos.com/api-reference/graphql/apicallnotificationinputtype.html
https://take.ms/6TC7N

https://documentation.platformos.com/api-reference/graphql/user.html
https://take.ms/lByKe

**Comment by diana-lakatos** [comment]
I fixed the one in the Angular use case, all others are in the new GraphQL API Reference, so @pavelloz can fix.

**Comment by pavelloz** [comment]
Fixed https://documentation.platformos.com/api-reference/graphql/rootquery.html
