### ISSUE TITLE
Use Case: Scoring 100/100 in Google Lighthouse

### ISSUE THREAD

**Issue by diana-lakatos** [Platform-OS/platformos-documentation#1081]
Note: using our Documentation and marketing sites as proof-points

**Comment by pavelloz** [comment]
I dont think there is anything to write about to be honest. We just didn't include any heavy things to break it.

Its popular misconception that people do good performance scores... Its the other way around. Web is natively 100/100, just devs are breaking them by including a lot of bloat. We didnt include a lot of bloat in this case, so its fast.

Additionally, https://documentation.platformos.com/best-practices/performance/code-quality-performance - all this still applies
