### ISSUE TITLE
Bridge gap between Build a ToDo List App part 1 and part 2 

### ISSUE THREAD

**Issue by diana-lakatos** [Platform-OS/platformos-documentation#1104]
New user feedback from onboarding user research:

User was confused when the end of part 1 left you with a different code base than the start of the part 2. This could be confusing for inexperienced or new pOS users. If the user doesn’t download the code just tries to figure it out on his own, it’s harder to figure out why it isn’t working in the second part.

**Comment by pavelloz** [comment]
Done 
https://github.com/mdyd-dev/nearme-documentation/commit/ab9fcee0200161828b3a9eef128552e6ebd2c7d7
