### ISSUE TITLE
[User Uploads] Wrong code formatting

### ISSUE THREAD

**Issue by jnorbert** [Platform-OS/platformos-documentation#1151]
URL: https://documentation.platformos.com/developer-guide/user-uploads/user-uploads

Actual result:
<img width="2550" alt="code" src="https://user-images.githubusercontent.com/13810654/84109046-0eac3c00-aa22-11ea-8896-9f94101a41f3.png">

**Comment by diana-lakatos** [comment]
Thank you @jnorbert! 

I fixed it: https://documentation.platformos.com/developer-guide/user-uploads/user-uploads

![Screenshot 2020-06-09 at 8 04 57](https://user-images.githubusercontent.com/4191691/84111818-f3dcc600-aa27-11ea-9eb2-11602ba99fa0.jpg)
