### ISSUE TITLE
Fix Hello, World! error

### ISSUE THREAD

**Issue by diana-lakatos** [Platform-OS/platformos-documentation#1160]
User feedback: 
On step 6, after deploying and refreshing the page, I got a liquid error 

![nyJCtJ](https://user-images.githubusercontent.com/4191691/84661695-0325ad00-af1b-11ea-9d8e-2994021bd297.png)

Header and footer partials were not generated with pos-cli init 

![xC0fGR](https://user-images.githubusercontent.com/4191691/84661788-22243f00-af1b-11ea-971c-eda383e1795f.png)

@jnorbert Could you please test this? Thank you!

**Comment by jnorbert** [comment]
@diana-lakatosI've checked the page in two scenarios:
1. After onboarding
2. The default page after `post-cli init`

In both cases, everything worked as expected.

Test results:
<img width="2557" alt="Screenshot 2020-06-15 at 16 41 26" src="https://user-images.githubusercontent.com/13810654/84672080-6833cf80-af28-11ea-9334-a9f37bf27022.png">

<img width="2558" alt="Screenshot 2020-06-15 at 16 47 50" src="https://user-images.githubusercontent.com/13810654/84672104-6d911a00-af28-11ea-9782-99823ad2ccad.png">

**Comment by diana-lakatos** [comment]
Thank you @jnorbert! That means that this should be fixed by fixing #1159.

**Comment by pavelloz** [comment]
Those files were missing, so i just removed 1col page since we didnt use it in our example anymore.

https://github.com/mdyd-dev/directory-structure/commit/bee01634ffa8c5f1da27b6902404c255344dc402

**Comment by diana-lakatos** [comment]
Thank you!
