### ISSUE TITLE
Update Build a ToDo List App part 1

### ISSUE THREAD

**Issue by diana-lakatos** [Platform-OS/platformos-documentation#1161]
User feedback: 
I tried to follow the “Build a To Do” App tutorial. 
Created a file application.liquid  

![8VAb6r](https://user-images.githubusercontent.com/4191691/84661979-6e6f7f00-af1b-11ea-916e-30c8ec5f9cfd.png)

Then an index.liquid 

![dycNnQ](https://user-images.githubusercontent.com/4191691/84662047-8ba44d80-af1b-11ea-92d7-9197bda55c65.png)

Then I deployed but when I go to the root of my instance, I got this:

![jXjyS2](https://user-images.githubusercontent.com/4191691/84662131-aaa2df80-af1b-11ea-9e0d-799eb43a05c3.png)

Since I have experience with pOS, I know that this is incorrect and how to fix it but I think for a new user’s point of view this is going to be confusing.

**Comment by pavelloz** [comment]
I think this has been fixed https://github.com/mdyd-dev/desksnearme/pull/9728
If thats not it, i have no idea what the issue, i created layout + page and deployed it ~1000 times and it works.
