### ISSUE TITLE
Deprecated filters - mark

### ISSUE THREAD

**Issue by pavelloz** [Platform-OS/platformos-documentation#1164]

**Comment by diana-lakatos** [comment]
Related to:
#535 
#538 
#540

**Comment by diana-lakatos** [comment]
User feedback:

> Instead of moving deprecated filters to the end, can you leave them in place and just add a deprecated tag to them? If you add the tag to the nav as well, it won’t be an issue for people.

> You could also hide deprecated tags by default, and have a nav filter for showing them. But I think this undoes some of the good of leaving them in place.
