### ISSUE TITLE
Add new tags to api reference

### ISSUE THREAD

**Issue by piotrze** [Platform-OS/platformos-documentation#1183]
We have updated liquid to newest version which includes new tag
- liquid https://shopify.dev/docs/themes/liquid/reference/tags/theme-tags#liquid

**Comment by diana-lakatos** [comment]
@piotrze Which category should I put this new tag into?
(Or should I create a new Tags: Theme category?)

![Screenshot 2020-08-05 at 14 16 18](https://user-images.githubusercontent.com/4191691/89411799-4e438b80-d726-11ea-9acc-cd6817e00b17.jpg)

Thank you!

**Comment by piotrze** [comment]
![image](https://user-images.githubusercontent.com/96238/89884320-a9173000-dbc9-11ea-929e-06cf5d637297.png)
@diana-lakatos On shopify they keep it with `render` tag which is successor of `include` tag. So I would put it in `Tags: include`.

We should note new way a writing liquid in https://documentation.platformos.com/api-reference/liquid/introduction
and we should start rewriting our examples to new syntax.

**Comment by piotrze** [comment]
@diana-lakatos We should also add `echo` tag to documentation.
https://shopify.dev/docs/themes/liquid/reference/tags/theme-tags#echo

**Comment by diana-lakatos** [comment]
@piotrze I added the `echo` tag, too in this PR https://github.com/mdyd-dev/nearme-documentation/pull/1190

I ended up putting it in Tags: Theme, because otherwise echo would have been the only one on the page (and because I wrote it before your comment here).

**Comment by diana-lakatos** [comment]
> We should note new way a writing liquid in https://documentation.platformos.com/api-reference/liquid/introduction
> and we should start rewriting our examples to new syntax.

Thank you! I opened separate tickets for these tasks:
#1191 
#1192
