### ISSUE TITLE
Add example to Using the GeoJSON Format for Geolocation

### ISSUE THREAD

**Issue by diana-lakatos** [Platform-OS/platformos-documentation#1186]
When we implemented solution based on function ST_DWithin or replace ST_DistanceSphere to ST_Distance to be able to use Polygons, update example to show this: https://documentation.platformos.com/developer-guide/models/using-geojson-format-geolocation

**Comment by godot** [comment]
https://github.com/mdyd-dev/desksnearme/pull/9991
