### ISSUE TITLE
Rewrite Liquid examples to new syntax

### ISSUE THREAD

**Issue by diana-lakatos** [Platform-OS/platformos-documentation#1192]

**Comment by piotrze** [comment]
@diana-lakatos Any ETA on this?

**Comment by diana-lakatos** [comment]
I'm going through the examples by section and category, and will connect PRs to this ticket. 

- [x] **Get Started**
- [x] **Best Practices**
- [x] **Use Cases**

**Developer Guide**
- [x] about-platformos
- [x] activity-feeds
- [x] apis
- [x] assets
- [x] authorization-policy
- [x] blog
- [x] data-import-export
- [x] data-management
- [x] forms
- [x] identity-providers
- [x] integrations
- [x] modules
- [x] notifications
- [x] pages
- [x] partner-portal
- [x] payments
- [x] platformos-workflow
- [x] pos-cli
- [x] pos-product-marketplace
- [x] properties
- [x] records
- [x] search
- [x] sendgrid-email-marketing
- [x] translations
- [x] user-uploads
- [x] users
- [x] variables

**Comment by diana-lakatos** [comment]
- [X] Get Started
- [ ] Developer Guide
- [ ] Best Practices
- [ ] Use Cases
