### ISSUE TITLE
Update function and return tag documentation

### ISSUE THREAD

**Issue by diana-lakatos** [Platform-OS/platformos-documentation#1217]
Update the documentation of the following tags:

- https://documentation.platformos.com/api-reference/liquid/platformos-tags#function
Add: 
This tag is currently called `function_rc`, where rc stands for release candidate as this is an experimental feature and eventually this tag will be renamed to `function`.

- https://documentation.platformos.com/api-reference/liquid/platformos-tags#return 
Add: 
This tag is currently called `return_rc`, where rc stands for release candidate as this is an experimental feature and eventually this tag will be renamed to `return`.

**Comment by pavelloz** [comment]
Its `function_rc`

**Comment by diana-lakatos** [comment]
@pavelloz Thank you, I updated the text.

**Comment by diana-lakatos** [comment]
rc removed from tags
