### ISSUE TITLE
Explain property argument in the compact filter

### ISSUE THREAD

**Issue by diana-lakatos** [Platform-OS/platformos-documentation#1221]
Feedback on: 
https://documentation.platformos.com/release-notes/18-MAY-2020

User feedback:
Hi, Could the Liquid docs be updated to explain how to use: "added property argument in the compact filter to be better compatible with native Liquid implementation" Thanks!

Note:
I think it could help if we added an example that uses the property argument here: https://documentation.platformos.com/api-reference/liquid/platformos-filters#compact

**Comment by pavelloz** [comment]
I have no idea what that means
