### ISSUE TITLE
Fix typo in platformOS filters

### ISSUE THREAD

**Issue by diana-lakatos** [Platform-OS/platformos-documentation#1222]
{{ '2018-05-30T09:12:34.000-07:00' | strftime: '%Y-%m-%d %H:%M', 'Pacific/Apia' }} => 2018-05-31 05:12

https://documentation.platformos.com/api-reference/liquid/platformos-filters

**Comment by pavelloz** [comment]
Where is typo?

**Comment by diana-lakatos** [comment]
@pavelloz I asked the user who reported it, will post his answer as soon as he replies.

**Comment by pavelloz** [comment]
Example survey before creating issue on GH:
<img width="777" alt="image" src="https://user-images.githubusercontent.com/546845/92120964-02096b00-edfa-11ea-8c0c-5c7474a7899f.png">

Source: https://www.platformos.com/issue-report

**Comment by diana-lakatos** [comment]
@Nagygyorgy How could we incorporate this into the feedback block on our documentation pages? Let's discuss! Thank you!

**Comment by diana-lakatos** [comment]
I got the answer from the user, it was a misunderstanding. Closing the issue, but we should discuss how to get more information on reported issues. Thanks!
