### ISSUE TITLE
Rename documentation repository

### ISSUE THREAD

**Issue by diana-lakatos** [Platform-OS/platformos-documentation#1227]
From: https://github.com/mdyd-dev/nearme-documentation
To: https://github.com/mdyd-dev/platformos-documentation

**Comment by pavelloz** [comment]
Maybe just `documentation`?

**Comment by Developer-DNM** [comment]
IMHO having https://github.com/mdyd-dev/platformos-documentation will be better for seo as this is a public repo and we want to rank as high for our own documentation site as possible.

**Comment by pavelloz** [comment]
So maybe we should start with changing organization name, `mdyd-dev` isnt particularly seo friendly

**Comment by Developer-DNM** [comment]
I agree however changing the organization name is much more difficult and far reaching than simply adding platform OS to the repo name so let's start with platform OS documentation repo.

Later we will change the old name and all associated repos.

**Comment by Developer-DNM** [comment]
This will be more of an agile iterative name change winky smile

**Comment by Developer-DNM** [comment]
@Slashek what's are the implications and effort involved in changing the org name sooner than later?

If it's two onerous right now we can wait but would be good to understand the effort.

**Comment by pavelloz** [comment]
It wont get easier with time and we are already waiting for years with it.

**Comment by Developer-DNM** [comment]
I'II let @Slashek make the call - we're in the middle of the Community MVP and dont want to slow that down.  If we have to wait another couple of weeks, so be it.

**Comment by pavelloz** [comment]
Done
