### ISSUE TITLE
Use case: Notifications - Activity Feeds

### ISSUE THREAD

**Issue by diana-lakatos** [Platform-OS/platformos-documentation#1231]
based on Golfstix notifications

**Comment by hosszukalman** [comment]
Maybe it's already fixed in #1248 , isn't it?

**Comment by diana-lakatos** [comment]
Yes, the information we were planning is already included in:
https://documentation.platformos.com/developer-guide/activity-feeds/activity-feeds
https://documentation.platformos.com/developer-guide/activity-feeds/implementing-activity-feeds
https://documentation.platformos.com/developer-guide/activity-feeds/handling-read-activites
