### ISSUE TITLE
Document the pOS Email Marketing module

### ISSUE THREAD

**Issue by diana-lakatos** [Platform-OS/platformos-documentation#1235]
- [x] description for the Module Marketplace (description, installation instructions, setup, configuration)
- [x] documentation topics on the documentation site (will be linked to on the Module Marketplace)
- [x] add installation tutorial to module description page

**Comment by JJBragg** [comment]
https://partners.platformos.com/marketplace/pos_modules/98

**Comment by diana-lakatos** [comment]
@JJBragg  Thank you! I reviewed and edited.
