### ISSUE TITLE
Filters: change `any` to `contains`

### ISSUE THREAD

**Issue by onecreative** [Platform-OS/platformos-documentation#1240]
If `contains` is available to use, it would be a much more recognizable filter name than `any`. Since `contains` is already used for this purpose in `if` statements, people will identify its purpose immediately. If it isn't available to use, `includes` would be the next best option because it does the equivalent function in js.

`any`, of course, would remain as an alias for backwards compatibility.

**Comment by diana-lakatos** [comment]
If this is still an issue, please reopen this ticket.
