### ISSUE TITLE
Add escape_once and ifchanged Liquid filters to documentation 

### ISSUE THREAD

**Issue by diana-lakatos** [Platform-OS/platformos-documentation#1265]
User feedback: 

https://shopify.github.io/liquid/filters/escape_once/ 
- this works on platformOS but is not documented 

Template: 
```
{% assign list = "1,3,2,1,3,1,2" | split: "," | sort %}
{% for item in list -%}
    {%- ifchanged %} {{ item }} {% endifchanged -%}
{%- endfor %}
```

`ifchanged` is also undocumented, but you might implement it in a different way, so please add example

**Comment by pavelloz** [comment]
<img width="555" alt="image" src="https://user-images.githubusercontent.com/546845/95916849-9546a080-0da9-11eb-9835-8cb65bfef305.png">
this might be a better explanation of ifchanged

**Comment by richxrich** [comment]
Two messages seemed to have gotten merged, there are two undocumented tags in this one ticket escape_once and ifchanged

**Comment by hosszukalman** [comment]
I checked `escape_once` but `{% log "1 < 2 & 3" | escape_once %}`'s result is `info: 1 < 2 & 3` so I think `escape_once` is not supported.

**Comment by richxrich** [comment]
@hosszukalman : It is supported, look at your source (not inspector) to see it working:

```
escape: {{ "Have you read 'James & the Giant Peach'?" | escape | escape }}<br>
escape_once: {{ "Have you read 'James & the Giant Peach'?" | escape_once | escape_once }}<br>
```

Output:
```
escape: Have you read &amp;#39;James &amp;amp; the Giant Peach&amp;#39;?
escape_once: Have you read 'James &amp; the Giant Peach'?
```

Edit: Also it may not be working in the liquid inspector (different engine?), but it does work on staging

**Comment by richxrich** [comment]
@pavelloz : Although the bigger question is why escape escaped ' and escape_once didn't
