### ISSUE TITLE
Full-text search for models/users

### ISSUE THREAD

**Issue by Slashek** [Platform-OS/platformos-documentation#1280]
Currently only deprecated `customizations` and `people` have full-text search capability. As a developer, I would like to be able to use non-deprecated queries for full-text search.

**Comment by Developer-DNM** [comment]
@JJBragg Are there Jira Service Desk comments from Channel Partners that can be appended here?

**Comment by JJBragg** [comment]
I see mention of this here: https://near-me.atlassian.net/jira/servicedesk/projects/NMS/queues/custom/84/NMS-4098, https://github.com/mdyd-dev/desksnearme/issues/9862, https://platformos.slack.com/archives/C01D86WC42Z/p1603795167007900,

**Comment by enginate** [comment]
@Slashek Any update on the status of this?  Just trying to gauge viability for a project that's launching in the next month.

**Comment by mattwalter91** [comment]
They'd planned to release before New Year, but nothing has been mentioned. I assume very close...

**Comment by Slashek** [comment]
Oh, we did release it before the new year - it's already there - see https://documentation.platformos.com/api-reference/graphql/recordsfilterinput.html (`fulltext` argument). 

Currently, we are doing some optimization work behind the scenes and applying it to our Marketplace Template.

**Comment by mattwalter91** [comment]
Silently. It was released 7 minutes ago as far as this thread is concerned.

**Comment by enginate** [comment]
Wow - that's great, unexpected news.  Thanks all!
