### ISSUE TITLE
Downloadable modules in Marketplace

### ISSUE THREAD

**Issue by niko-cbo** [Platform-OS/platformos-documentation#1284]
[JIRA Ticket Link](https://near-me.atlassian.net/servicedesk/customer/portal/1/NMS-4357)

As a developer, I would like to be able to download a module instead of installing so that I can manually merge it in my existing project.

**Comment by richxrich** [comment]
How would that work for private files?

**Comment by niko-cbo** [comment]
Hi Rich, 

To add more context, We had this option in the BC App Store and it was really handy when you don’t want anything installed, but want to sell things.

Examples could be a zip file of code, documents templates, graphics, videos, etc.

Our particular example is offering our eCommerce code that can be retro-fitted manually to a website. We can’t install it directly on an exisiting site as it will break the site as some of the files would be overwritten.

**Comment by Slashek** [comment]
@niko-cbo closing the issue for now. You can already do this with pos-cli module pull command, just note there won't be any private files. If you would like to kick off an additional discussion, please visit  https://community.platformos.com :)
