### ISSUE TITLE
Logo partial is missing on the autogenerated Graphql reference page

### ISSUE THREAD

**Issue by chrisdanek** [Platform-OS/platformos-documentation#1305]
https://documentation.platformos.com/api-reference/graphql/presigneduploadurl.html

<img width="490" alt="Screenshot 2020-11-13 at 18 29 51" src="https://user-images.githubusercontent.com/1758834/99102357-407f8b00-25de-11eb-958b-c0a808b7a447.png">

**Comment by pavelloz** [comment]
fixed
