### ISSUE TITLE
improve the way we sanitize output

### ISSUE THREAD

**Issue by Slashek** [Platform-OS/platformos-documentation#1312]
See related documentation article https://documentation.platformos.com/api-reference/liquid/sanitization#content

There are multiple issues with the current implementation, which we would like to fix. We will do it in a backward-compatible manner, which means all existing sites will keep behaving the same way they do right now. As part of this task, we'll create a new `app/config.yml` which will allow people to control the behavior of the new sites (documentation will be provided separately). Here are some of the most common issues reported by our Partners:

1. confusing auto-correcting HTML

Consider the following example:
```
{{ 'Please use modules/<module_name>/<file_name>' }}
```

You would expect to see exactly this rendered, however with the old sanitizer, you would see:

```
Please use modules/<module_name>/<file_name></file_name></module_name>
```

because of the auto-correct feature. This is by far the most confusing behavior of the current system.

2. not escaping quotes

This makes it harder to prevent some of XSS vulnerabilities, like for example:

```
{% capture href %}#" onclick="alert('hello'){% endcapture %}
<a href="{{ href }}">Click me </a>

In the new system, the JS will not be executed. In the old system, you would need to add filters to make sure JS is not executed.

3. rendering some tags as HTML automatically

Consider the following example:

```
{{ 'This is <div>hello</div>' }}
```

This would be rendered as HTML (hence auto-correct feature), but some other tag, which is considered unsafe (like `script`) will be escaped. In some scenarios this can be problematic - rendering HTML should only happen if explicitly allowed (for example via `sanitize`) tag.

**Comment by richxrich** [comment]
Put @Slashek on the frontline more often to see the issues :)

**Comment by Slashek** [comment]
The new escaping engine has been deployed. To enable it, create `app/config.yml` with content: ` escape_output_instead_of_sanitize: true`
