### ISSUE TITLE
Write topic about generating a pdf without user submission

### ISSUE THREAD

**Issue by diana-lakatos** [Platform-OS/platformos-documentation#1323]
User request: 

> If it is possible to generate a pdf without a user submission, a great example would be invoices. A common scenario (and something I'll need to tackle) is an invoice being generated after an order. So, when a user logs into their account they see their invoices. This would be an awesome "how to".

Other use cases:

> generate a "certificate of completion" pdf for users after they accomplish something. That certificate is automatically customized with the user's name, date, etc.

> create Invoices, Picking Slips and Delivery labels for our Ecommerce solution

The current documentation only covers the use case when there is user submission.

**Comment by onecreative** [comment]
I thought this wasn't currently possible with pOS.

**Comment by Developer-DNM** [comment]
@onecreative This is soon to graduate to production.
