### ISSUE TITLE
add_hash_key should allow for the third argument to be missing

### ISSUE THREAD

**Issue by onecreative** [Platform-OS/platformos-documentation#1327]
Sometimes I need to create the hash key in one step and add something to it in another. I propose we change the current behavior to allow for that. 

Example:
```
{%- assign output = '{}' | parse_json -%}
{% if errors %}
	{%- response_status 400 -%}
	{% assign output = output | add_hash_key: 'errors' %}  <--
	{% for error in errors %}
		{%- hash_assign output['errors'][error[0]] = error[1] -%}
	{% endfor %}
{% else %}
	{%- response_status 204 -%}
{% endif %}
{{output}}
```

Please don't point out that in my scenario I could do this a different way. It's just an example to show that sometimes we might not have a value to add to the hash right away.

**Comment by richxrich** [comment]
hash_assign also adds if it doesn't already exist, I dont understand why you would want to create an empty hash key just to add something to it later

**Comment by onecreative** [comment]
I would have deleted this issue if I could. It's not about "empty". It's about creating an object without properties. `{}` not `null`.

**Comment by richxrich** [comment]
I think you need to present use cases :)

**Comment by onecreative** [comment]
I closed it.

**Comment by pavelloz** [comment]
It might be a good idea to do it the other way - put default value in a key that is expected, and remove it if something different than usual case happened.
