### ISSUE TITLE
new rand filter

### ISSUE THREAD

**Issue by onecreative** [Platform-OS/platformos-documentation#1329]
I think we should have a `rand` liquid filter. Here's a page that shows a workaround and also shows the reason Shopify removed this filter. But I think it would be good for us to have, simply because the server will be able to produce much more unique OTPs than I could using the workaround.

In my own test of producing 4 digit OTPs using the workaround mentioned in the article, 5.5% of the OTPs were a duplicate. Here's my test:
```
{% assign otps = '[]' | parse_json %}
{% for i in (1..1000) %}
	{% assign otp = 'now' | date: '%N' | modulo: 8999 | plus: 1000 %}
	{% assign otps = otps | add_to_array: otp %}
{% endfor %}
{%- log otps, type: 'otp' -%}
{%- log otps.size, type: 'otps.size' -%}
{% assign deduped = otps | uniq %}
{%- log deduped.size, type: 'deduped.size' -%}
```

Our version of `rand` could allow for devs to specify a character whitelist and total number of characters. I'm thinking something like:

- 4 characters long, using the characters provided => `{% assign otp = '0123456789' | rand: 4 %}`
- 6 characters long, using the characters provided => `{% assign otp = '0123abcdABCDE-&/)' | rand: 6 %}`
- 6 characters long with the default, alphanumeric => `{% assign otp = '' | rand: 6 %}`

This would be superior to our existing `random_string` filter, simply because it allows us to choose the character whitelist. A possible backwards compatible alternative to this would be to add a whitelist parameter to the end of the `random_string` filter. Maybe that's the better way to go.

**Comment by richxrich** [comment]
A combination of the random filter and regex should provide you with a complex and unique enough password.

**Comment by Slashek** [comment]
We already have a filter to generate random string securely https://documentation.platformos.com/api-reference/liquid/platformos-filters#random_string . It does not however allow you to provide your own character set. There's also https://documentation.platformos.com/api-reference/liquid/platformos-filters#uuid

**Comment by onecreative** [comment]
As I mentioned, I like the idea of extending `random_string`. It would be quite useful.

**Comment by Slashek** [comment]
You are right, removing the comment. A potential improvement I can see would be to allow not only hex strings but also alphanumerical as you mentioned. Also, UUID doesn't need to be a separate filter. But I am not sure about the custom alphabet. What would be the use case of generating a "secure" random string consisting only of digits and length of N?

**Comment by onecreative** [comment]
> But I am not sure about the custom alphabet. What would be the use case of generating a "secure" random string consisting only of digits and length of N?

Well, two points:

- It isn't necessarily about "secure". It could be about "unique".
- By allowing people to define their own whitelists, the filter becomes flexible enough for you to not need to know all the use-cases. It becomes a utility.

**Comment by DeanmvSG** [comment]
Also extending this would be a "random" input for GraphQL.  Sometimes we would like to pull an item out of a table but have only 1 of them at random on page load.

For example loading a "Special Offer" record for a page

(If this is a separate enough issue I can move it)

**Comment by onecreative** [comment]
@DeanmvSG I think that should be a separate issue.

**Comment by DeanmvSG** [comment]
Moved to Service Desk 👍

**Comment by diana-lakatos** [comment]
We've added the proper way of adding OTPs to the platform, the example of how to use this is in the template. If this is still an issue, please reopen the ticket.
