### ISSUE TITLE
[API reference page] Sticky in page navigation

### ISSUE THREAD

**Issue by Nagygyorgy** [Platform-OS/platformos-documentation#1330]
Based on user research results Developers spend the most time on the API reference pages. The results showed that it would make the experience of these long pages better if we could make the **in page navigation on the right side sticky**. So the user can see their actual position on the page and switch between items quickly if needed without scrolling on the top.

**Comment by z-x** [comment]
Fixed in https://github.com/mdyd-dev/platformos-documentation/pull/1541 and https://github.com/mdyd-dev/platformos-documentation/pull/1527
