### ISSUE TITLE
Contributors page - some contributor's name appears next to their picture instead of below

### ISSUE THREAD

**Issue by Nagygyorgy** [Platform-OS/platformos-documentation#1335]
In some cases, the contributor's name appears next to their picture instead of below. 
<img width="1113" alt="Screen Shot 2021-01-06 at 14 17 48" src="https://user-images.githubusercontent.com/3997812/103775047-cbed2980-502d-11eb-91bd-b68355352383.png">

https://documentation.platformos.com/community/contributors

Thanks

**Comment by z-x** [comment]
Fixed in https://github.com/mdyd-dev/platformos-documentation/pull/1545/files
