### ISSUE TITLE
Lack of syntax highligthing in liquid filters

### ISSUE THREAD

**Issue by piotrze** [Platform-OS/platformos-documentation#1354]
![image](https://user-images.githubusercontent.com/96238/106909689-d10ec880-6700-11eb-99f6-e6057f5e25cd.png)

**Comment by pavelloz** [comment]
![image](https://user-images.githubusercontent.com/546845/106910126-3662b980-6701-11eb-8cf9-d1c811758ba7.png)

Try turning your linux off and on again
