### ISSUE TITLE
Create new alert types: tutorial, concept topic

### ISSUE THREAD

**Issue by diana-lakatos** [Platform-OS/platformos-documentation#137]
Create two new types of alerts: 
* tutorial: curved arrow icon, white background 
![tutorial_icon](https://user-images.githubusercontent.com/4191691/42445811-951f6cac-8374-11e8-802f-80f21efd4920.png)

* concept: book icon, white background
![concept_icon](https://user-images.githubusercontent.com/4191691/42445810-9501c576-8374-11e8-8d6b-09fe6ba4b40d.png)

Attaching two examples of use from a wireframe for context:

![tutorial_alert](https://user-images.githubusercontent.com/4191691/42446118-725a3dfe-8375-11e8-90c5-5d4549219f90.png)
![concept_alert](https://user-images.githubusercontent.com/4191691/42446119-727d2382-8375-11e8-9134-1f357b018094.png)

Thank you!

**Comment by pavelloz** [comment]
Done

Live: https://documentation.oregon.near-me.com/use-cases/building-blog
Preview: ![image](https://user-images.githubusercontent.com/546845/42474346-9c008602-83c7-11e8-875c-775172cbc8fc.png)

**Comment by diana-lakatos** [comment]
They should be the other way around: curved arrow for tutorials, book for concepts.

**Comment by diana-lakatos** [comment]
Fixed, thank you.
