### ISSUE TITLE
Move Notifications out from Forms section.

### ISSUE THREAD

**Issue by piotrze** [Platform-OS/platformos-documentation#1391]
We should move notifications to the different section, maybe create new one. Right now you can call notification with graphql  without forms at all for this. I also remember from talk with some potential partner developers that they were asking about api calls, emails and it was hard for them to find it.

![image](https://user-images.githubusercontent.com/96238/115208175-952eb100-a0fc-11eb-8b61-48dfff6adf10.png)

**Comment by pavelloz** [comment]
True, true.

**Comment by diana-lakatos** [comment]
Plan: GP initiative
