### ISSUE TITLE
Add t_escape filter to docs

### ISSUE THREAD

**Issue by diana-lakatos** [Platform-OS/platformos-documentation#1403]
Announced in this release note: https://documentation.platformos.com/release-notes/31-MAY-2021

**Comment by pavelloz** [comment]
It will add itself automatically after its on production :)

**Comment by pavelloz** [comment]
It is live now: https://documentation.platformos.com/api-reference/liquid/platformos-filters#translate_escape-aliases-t_escape
We probably need better description and examples, but the mechanism is working

**Comment by diana-lakatos** [comment]
Thank you @pavelloz
