### ISSUE TITLE
Add documentation of where filter

### ISSUE THREAD

**Issue by diana-lakatos** [Platform-OS/platformos-documentation#1414]
https://shopify.github.io/liquid/filters/where/

**Comment by diana-lakatos** [comment]
@pavelloz Please confirm that we need to add this and I will add it. Thank you!

**Comment by pavelloz** [comment]
@piotrze can we check why it is not generated automatically?
Its native filter from liquid [4.0.2](https://shopify.github.io/liquid/filters/where/) and it looks like we are on [4.0.3](https://github.com/mdyd-dev/desksnearme/blob/a55ecbb200cab3636bebad60c85de97f9613ea99/Gemfile.lock/#L1-L15).

**Comment by diana-lakatos** [comment]
@pavelloz This would go on this page, wouldn't it? This is not auto-generated, only the pOS-specific filters.
https://github.com/mdyd-dev/platformos-documentation/blob/master/app/views/pages/api-reference/liquid/filters.liquid

**Comment by pavelloz** [comment]
Ouh, that explains it :)
I just need to add it.
