### ISSUE TITLE
Update liquid types

### ISSUE THREAD

**Issue by piotrze** [Platform-OS/platformos-documentation#1429]
https://documentation.platformos.com/api-reference/liquid/types#nil

I think we should replace `nil` with `null`. It will be then consistent with graphql and json

We should also add hash/object type with examples how to create it. Not sure which word is better, we already use `hash` in liquid fitlers.

**Comment by pavelloz** [comment]
`object` is more familiar for people with JS background, but hash might be more accurate (hash does not have methods, like objects in js can)
