### ISSUE TITLE
sort_by filter uses wrong filter in example code

### ISSUE THREAD

**Issue by JoshCarterWeb** [Platform-OS/platformos-documentation#1462]
The sort_by filter uses the hash_sort filter in it's example, which doesn't accept any arguments

[Source](https://documentation.platformos.com/api-reference/liquid/platformos-filters#sort_by)

**Comment by diana-lakatos** [comment]
Thank you for reporting this @JoshCarterWeb. 
@pavelloz Can you please take a look and fix this?

**Comment by andrew-3** [comment]
I created internal PR: #10505 which fixes this.

Thanks!
