### ISSUE TITLE
Update hash_sort filter

### ISSUE THREAD

**Issue by diana-lakatos** [Platform-OS/platformos-documentation#1484]
User feedback:

> Message: Please can you add expected return from hash_sort filter?
> Feedback to: [https://documentation.platformos.com/api-reference/liquid/platformos-filters](https://u583609.ct.sendgrid.net/ls/click?upn=V9k-2BIPHvgpBuAOsUk9M1igr5VboGOHwAg8FhEnYEi6pWyGwC02UIof3psbHfzBbPzJcHqsQVrBfqgrtguNXmixXmuWqa3nGGsCvERAonh6EGW4JtcnFcWUhPhHX4qQytBWie_B9j3yDr-2FeZ-2Bnsw7bZ8ReE3UIRBC8BKFGaYz7MG1LIYdwYrRbHHh6QTGEhKPWn91-2BKlUKcTFi8oiih96VxDfGmd3Kj1HUaGRJEsQXSZDsi44600jQ6sTycDfUCgZAOg9w15PUUQTqyGrfzBot48iDA-2FnNsioxWDK1-2BMtAgVH6C9LhLAejwbXCao-2Fem8B2pmuD74eZNhYsXu-2FnvrCxtUvfmI3AASwmRrVsHqdzyjpRg7o-3D)

Improve documentation by adding an example, for example:

> {"a": 1, "c": 2, "b": 3} => {"a": 1, "b": 3, "c": 2}
> It sorts the hash by key, not value.

**Comment by Slashek** [comment]
Done
