### ISSUE TITLE
Recaptcha v3 source code not found

### ISSUE THREAD

**Issue by diana-lakatos** [Platform-OS/platformos-documentation#1489]
User feedback: 

> Email: | tommy@easywebsitemanager.com.au
> Message: | The source code not found
> Feedback to: | https://documentation.platformos.com/developer-guide/integrations/adding-recaptcha-v3-spam-protection

The source code link https://github.com/mdyd-dev/platformos-examples/tree/master/modules/signin_recaptcha does not work.

**Comment by Slashek** [comment]
Dead link has been removed, replaced example with hcaptcha
