### ISSUE TITLE
Links broken on 

### ISSUE THREAD

**Issue by jacobshea** [Platform-OS/platformos-documentation#1642]
Links broken on https://documentation.platformos.com/api-reference#graphql-api page section. I don't know the new URLs to update on the repo.

* Bad link [GraphQL API Reference](https://documentation.platformos.com/api-reference/graphql/graphql)
* Bad link [Queries](https://documentation.platformos.com/api-reference/graphql/rootquery)
* Bad link Root Mutation [Mutations](https://documentation.platformos.com/api-reference/graphql/rootmutation) Root Mutation

**Comment by LukeBroadway** [comment]
Links have been fixed
