### ISSUE TITLE
Add link to Contributor Guide to contribute section

### ISSUE THREAD

**Issue by diana-lakatos** [Platform-OS/platformos-documentation#1644]
Add a link to the Contributor Guide to the Contribute to this page section. The copy could be: "How to contribute" or "Contributor Guide". 
<img width="1096" alt="Screenshot 2023-08-23 at 15 17 51" src="https://github.com/mdyd-dev/platformos-documentation/assets/4191691/7867ae78-f88d-4422-b8f8-fc5a99b7f003">

@GyongyGora Could you please create a design that shows what it could look like? Thank you!

**Comment by GyongyGora** [comment]
@diana-lakatos 

I created 2 versions:
https://www.figma.com/file/3M4tJDUtQEB90cIqybeV4P/Doc-site-updates?type=design&node-id=401%3A204&mode=design&t=8a441g6iXMupfK20-1

v1. Consistent with other similar sections (e.g. on landing page). This has a link under the icon, but this way the 2 columns have different height and look a bit different visually.
v2. With a ? icon that could display a default tooltip when the users hovers it. In this case the 2 columns look more similar.

**Comment by diana-lakatos** [comment]
@GyongyGora Thank you very much! They both look great but I'd choose v2 because it's more subtle.

**Comment by LukeBroadway** [comment]
I can't access the figma design

**Comment by GyongyGora** [comment]
> I can't access the figma design

@LukeBroadway Could you please check it using this link? https://www.figma.com/file/jGVHdStunTaBLMWXINGZUK/pOS-docs-design-(3)?type=design&node-id=1551%3A2102&mode=design&t=pVzVVBMxfTJiyBrn-1

I added you to Figma and sent an invite to the file too. Hopefully it will work now! :)

**Comment by LukeBroadway** [comment]
Added the icon and correct linking with some help from Lukasz

**Comment by LukeBroadway** [comment]
Maybe the icon is too big though? Let me know

**Comment by GyongyGora** [comment]
Yes, it should be smaller, 20x20px only (now it is 32x32) and grey. Thank you! :) 

![question-circle](https://github.com/mdyd-dev/platformos-documentation/assets/57356652/61f67ca2-f76f-4ef8-8f71-06c29463280c)
![question-circle](https://github.com/mdyd-dev/platformos-documentation/assets/57356652/3913e973-778f-4d24-b279-3ebe9127b32f)

**Comment by LukeBroadway** [comment]
Yep just fixed. I exported the wrong icon svg data (used the spreadsheet one instead of the edited one you linked) the position/size looks good on windows and phone view
