### ISSUE TITLE
pOS Kits not visible in main manu

### ISSUE THREAD

**Issue by JakubMaziarz** [Platform-OS/platformos-documentation#1652]
![image](https://github.com/mdyd-dev/platformos-documentation/assets/92295710/e9e736da-32eb-4564-a5e0-f6292da003b7)

**Comment by JakubMaziarz** [comment]
It should lead to this page: https://documentation.platformos.com/kits as it's top of the menu but inaccessible via sub-pages of pOS Kits

**Comment by LukeBroadway** [comment]
Added pOS Kits to header
