### ISSUE TITLE
Effective dev using poscli page

### ISSUE THREAD

**Issue by JakubMaziarz** [Platform-OS/platformos-documentation#1670]
https://documentation.platformos.com/developer-guide/pos-cli/effective-development-using-pos-cli

Something is missing here in the section for concurrently - a picture? link?
![image](https://github.com/mdyd-dev/platformos-documentation/assets/92295710/6396ea27-7667-47e9-b7b0-d40d1dbb0db5)

**Comment by Slashek** [comment]
fixed
