### ISSUE TITLE
Content and format changes

### ISSUE THREAD

**Issue by digitalfuel** [Platform-OS/platformos-documentation#194]
The docs are great. Thanks for all the work on these.

Below are a few things that I think need updating. 

## Custom_model_types

https://documentation.platform-os.com/reference/custom-model-types/custom-model-types

Configuration Properties
instance_profile_types (changes to) user_profile_types 
relationship_types (delete)
transactable_types
order_types (Add)

-------------------------

## GUI

Marketplace-kit serve gui is not in the docs. Only mention seems to be in git repo

------------------------

## Liquid

I think the standard Liquid tag/filter etc found here https://shopify.github.io/liquid/ need to be in the pOS docs. Otherwise you are going to different places to find these. 

One thing the docs need in regards to liquid filters especially is grouping. With so many filters and the name not always being obvious (regex_matches and matches are both regex but are separated with matches not obvious by its name what it is) what they are it can be slow traversing doc. Groups like: Date, Math, abc, Format, Regex, javascript video etc These need to be thought out more but would help when look for the right filter. For Tags groups like Comment, Control Flow, iteration, raw, variable can be used like here https://shopify.github.io/liquid/

### Filters
#Intersection double up
#Videoify is missing Options Param data and any example.

Examples for params and options would help with understanding. Some are hard to work out without trial and error.

**Comment by pavelloz** [comment]
### CMT 

Yep, it needs to be updated, but first code needs to be updated. ;)

Order types are being deprecated, they are missing on purpose - we dont want anyone to rely on them.

Relationship types actually are something we need to document more, it probably will very important feature soon - correct me if im wrong @Slashek 

### GUI

I wrote a little article about GQL part`marketplace-kit gui serve` 

Hope that helps a little bit: https://documentation.platform-os.com/how-to/qa/developing-graphql-queries-using-marketplace-kit-gui

### Liquid

Yes, i think you are right. We wanted to avoid duplicating their content but at second thought it is kind of painful to roam around 2 different websites to read about one set of features.

### Filters

Yes, we were experimenting with autogenerating those docs (hence the docs are in html format, not usual liquid), but i think we are going to switch to our normal style - its much easier to maintain, modify and for community to collaborate in case of error.

Im not sure videoify will stay.

@piotrze intersection is duplicated 

---

Thank you for your input @digitalfuel , work is in progress :)

**Comment by digitalfuel** [comment]
### CMT

OK on good to know I think there is confusion here as I thought relationship was be depreciated. I though I heard it somewhere. 

### GUI

I totally missed that. I think I searched "serve gui" and got nothing which is because I had it back to front of course and when searching GUI there are loads of results. Would be good if this was somewhere in the doc like terminal commands as it is very cool and more could benefit especially with instance admin being depreciated.

Thank you for looking at these things so quickly :-)

**Comment by pavelloz** [comment]
### CMT

After consulting with @Slashek -- yes, you are right. :)


### GUI

You didnt miss it, i just wrote it :P

Yes, when Diana comes back from vacation we will discuss how to structurize all the CLI commands into article(s) so that its easy to find, reference and use.

**Comment by pavelloz** [comment]
I think we are missing action points and definition of done with this issue.

One thing noted is that we are missing mpkit commands explanation in docs - thats an actionable item.

I created https://github.com/mdyd-dev/nearme-documentation/issues/288 to make it more managable - if you have anything more specific Daniel, just create separate issues so it can be answered one by one (it might happen that part of big feedback wont be implemented/or was just a question)  

cc @digitalfuel  @diana-lakatos
