### ISSUE TITLE
Development workflow

### ISSUE THREAD

**Issue by pavelloz** [Platform-OS/platformos-documentation#281]
When i clicked Getting Started -> Development Workflow

It got me to https://documentation.platform-os.com/how-platformos-works/development-workflow

Which is "How PlatformOS works" category not getting started - sidebar or slug is wrong.

**Comment by diana-lakatos** [comment]
Fixed. 
As part of the How platformOS Works rewrites, this topic has been updated and moved to its final location: How platformOS Works -> platformOS Workflow -> Development Workflow.
https://documentation.platform-os.com/how-platformos-works/platformos-workflow/development-workflow
