### ISSUE TITLE
Add built-in liquid tags documentation

### ISSUE THREAD

**Issue by pavelloz** [Platform-OS/platformos-documentation#282]
Since they don't change like... ever, it can be hardcoded next to autogenerated ones.

Note: Remember to write about for/with @ include.

**Comment by lemingos** [comment]
Ever? I think we had a few changes over time.
Maybe we could move each tag to it's own page, and then at the top of the page have autogenerated part and after that examples section?
Plus you can add the comment about for/with in the code so it's documented there as well and will be included in the docs.

**Comment by pavelloz** [comment]
If we had few changes in 5 years then its not worth doing autogeneration mechanism for those exceptions.

From what i can tell we try very hard to not break default liquid behavior (which is a good practice).

Upfront cost and then maintenance cost for sure is higher than any benefit it can provide.

**Comment by pavelloz** [comment]
PS. No, you cant write note about for/with in the code, unless you want to fork liquid gem and maintain it afterwards, which seems like another time not well spent for not much of a benefit.

**Comment by pavelloz** [comment]
This is done.

Im extracting one tag from it because it will require special treatment: `include` - it will be described in separate article with explanation of our customizations regarding variables + examples with `with`/`for`.

Extracted to https://github.com/mdyd-dev/nearme-documentation/issues/393
