### ISSUE TITLE
Add ToC based on h2/h3 for easier content scanning

### ISSUE THREAD

**Issue by pavelloz** [Platform-OS/platformos-documentation#283]
Visuals TBD after MVP has been shipped.

**Comment by diana-lakatos** [comment]
Doing research on best practices.

**Comment by pavelloz** [comment]
1. Should be included only on api refs. where theres a lot of items on the page -- this dictate opt-in character of the feature (metadata)
2. its too distracting => no border, less text contrast

**Comment by pavelloz** [comment]
Merged
