### ISSUE TITLE
Write marketplace-kit commands series

### ISSUE THREAD

**Issue by pavelloz** [Platform-OS/platformos-documentation#288]
Explaining what each of them do (maybe even something like api reference).

We have couple of them explained in different places:
https://documentation.platform-os.com/get-started/deploying-syncing-changes
https://documentation.platform-os.com/get-started/creating-required-directory-structure
https://documentation.platform-os.com/tutorials/migrations/migrating-data

**Comment by diana-lakatos** [comment]
Thank you, added to topic queue.

**Comment by diana-lakatos** [comment]
After the Marketplace Kit documentation is reviewed and merged, we can consider updating the README for the Marketplace Kit GitHub repo with this (everything is included from the current README, and more).

**Comment by diana-lakatos** [comment]
https://documentation.platform-os.com/how-platformos-works/platformos-workflow/marketplace-kit

**Comment by pavelloz** [comment]
👍 :)
