### ISSUE TITLE
Inconsistent url vs article title

### ISSUE THREAD

**Issue by pavelloz** [Platform-OS/platformos-documentation#290]
In some places its components, in some workflow - something slipped when renaming probably.

![image](https://user-images.githubusercontent.com/546845/50378071-a7ca7580-0629-11e9-8d41-aaddeb9417bd.png)

**Comment by pavelloz** [comment]
Basic concepts vs basic building blocks
![image](https://user-images.githubusercontent.com/546845/50378078-d1839c80-0629-11e9-9c38-7388c062a4e1.png)

**Comment by pavelloz** [comment]
I think im going to write a test that will go through all sites and compare selected nav menu with title.

Or maybe its time to figure out a way to not hardcode the nav, because it was pretty obvious it will desynchronize with time.

**Comment by lemingos** [comment]
+1 Let's generate navigation based on page metadata and slug.

**Comment by diana-lakatos** [comment]
Inconsistencies popped up during the rewrite of _How platformOS Works_ topics. They are fixed now, so this issue can be closed. (To verify, check: https://documentation-staging.staging.oregon.platform-os.com/)  
I added a new issue to consider generating the navigation.
