### ISSUE TITLE
SMS on staging?

### ISSUE THREAD

**Issue by pavelloz** [Platform-OS/platformos-documentation#320]
Is this still true?

![image](https://user-images.githubusercontent.com/546845/51345879-7021e280-1a9c-11e9-8902-b29c3fea7564.png)

If yes, why do we have `enable_sms_and_api_workflow_alerts_on_staging` in PP?
If not, need to update article.

https://documentation.platform-os.com/tutorials/notifications/creating-sms-notification

**Comment by kv109** [comment]
@jnorbert You're testing staging instances on a daily basis. Do you use `enable_sms_and_api_workflow_alerts_on_staging` flag, and, if so, does it work?

**Comment by jnorbert** [comment]
@kv109 from what I remember sms doesn't work in test mode wich was used always on staging. This si reason why we never before checked sending sms from stg. @Slashek could you confirm it please?

**Comment by Slashek** [comment]
so yes, it is used and we have in logs information about api call / sms not being sent from staging due to the flag being disabled

**Comment by pavelloz** [comment]
Okay, so the last sentence that user needs to contact us is outdated?

Its enough to just flip the switch in PP and it will send live api calls/sms from staging?

**Comment by Slashek** [comment]
yes 🚀
