### ISSUE TITLE
Twilio integration

### ISSUE THREAD

**Issue by pavelloz** [Platform-OS/platformos-documentation#321]
This article:
https://documentation.platform-os.com/tutorials/notifications/creating-sms-notification

is talking in multiple places about twilio integration, but there is no twilio integration in PP and there is no instructions how to do it using config.

Sources:
![image](https://user-images.githubusercontent.com/546845/51349892-15da4f00-1aa7-11e9-9039-1109cd5fc610.png)

![image](https://user-images.githubusercontent.com/546845/51349901-1d99f380-1aa7-11e9-9125-22b8338b920c.png)

**Comment by pavelloz** [comment]
Feature to add integration appeared, so problem is gone, but to be consistent with other integrations it would probably help to add article how to get the data needed to enable it.

**Comment by Developer-DNM** [comment]
@pavelloz  - Twilio Integration function was re-enabled by @kv109 per: https://nearme.slack.com/archives/G9XNSSSMB/p1547852126142000?thread_ts=1547755831.123700&cid=G9XNSSSMB  

Not sure how it got removed, but yes, we should update the Docs as required.. cc @diana-lakatos

**Comment by kv109** [comment]
It was a feature flag mistake. At the beginning Twilio integration was supposed to be enabled only for pos instances.

**Comment by diana-lakatos** [comment]
PR #387

**Comment by pavelloz** [comment]
Lets go :-)
