### ISSUE TITLE
Grammarly check for all topics

### ISSUE THREAD

**Issue by diana-lakatos** [Platform-OS/platformos-documentation#327]
Review all existing topics in Grammarly, and fix any grammar mistakes. Includes all topics in:
- How platformOS Works
- Get Started
- Tutorials

Please continuously post the status of the checks to this issue.

**Comment by szabosteve** [comment]
I reviewed the following topics:

**Get started**:
* Accessing the Partner Portal
* Setting Up a Site on Our Platform
* Installing NPM on a Mac
* Installing NPM on Windows
* Installing the Marketplace Kit
* Updating the Marketplace Kit
* Creating the Required Directory Structure
* Deploying and Syncing Changes
* Development Workflow

**How platform.OS works**:
* About platform.OS
* platformOS Components
* Technologies

TBC

**Comment by szabosteve** [comment]
2nd batch.

**How platform.OS works**:
* Basic building blocks
* Glossary

**Tutorials**:
* Partner portal
    * Assigning a Billing Plan to an Instance
    * Changing the Partner of an Instance
    * Changing the Partner of a User
    * Checking the Releases of an Instance
    * Configuring a Test Email
    * Configuring www as the Default Domain
    * Creating a Billing Plan
    * Deleting an Instance
    * Deleting a User
    * Downloading the Codebase of an Instance
    * Finding Instances
    * Inviting a New User to the Partner Portal
    * Managing Integrations
    * Setting Up Instance and Partner Permissions for Users Outside of Your Own Partner
    * Setting Up a Production Domain
    * Setting Up a User's Instance Permissions
    * Setting Up a User's Partner Permissions
    * Unpublishing an Instance
    * Updating Instance Configuration
    * Updating an Instance
    * Updating a Partner

To be continued.

**Comment by szabosteve** [comment]
3rd batch.

* Pages and Layouts
    * Adding a New Page at a Custom URL
    * Injecting Dynamic Content into a Layout
    * Layouts
    * Metadata
    * Pages
    * Redirects 
    * Response Headers
    * Reusing Code Across Multiple Pages
    * Search by Content 

To be continued.

**Comment by szabosteve** [comment]
4th batch.

* Variables
    * Context variables
* Modules
    * Modules
    * Creating a Module
    * Sharing a Module
    * Installing a Module
* Assets
    * Assets
    * Using Static Assets on Your Pages
    * Adding Visuals to Pages: CSS
    * Adding Visuals to Pages: Liquid
    * Adding Visuals to Pages: Javascript
* SEO
    * Creating SEO Friendly URLs

TBC after pulling the repo again.

**Comment by szabosteve** [comment]
5th batch.

* SEO
    * Creating a Dynamic Sitemap
* AMP
    * Using a Static AMP Template
    * Converting AMP HTML Pages to Layouts and Pages
    * Feeding Data into AMP Pages with GraphQL
* Customizations
    * Building a Contact Form with Customization
    * Managing Customizations using AJAX (CRUD operations)
* User uploads
    * Uploading Files Directly to Amazon S3 Using HTML Form
    * Uploading Files Directly to Amazon S3 Using AJAX
    * Uploading Files Directly to Amazon S3 with User Profile Update

To be continued.

**Comment by szabosteve** [comment]
6th batch.

* Notifications
  * Notifications
  * Creating an Email Notification
  * Using Email Layouts
  * Creating an SMS Notification
  * Creating an API Call Notification
  * Parsing an API Response

* Search
  * Search
  * Narrowing Keyword Search
  * Creating a Search Query
  * Selecting Fields Available for Search
  * Keyword Match Type
  * Filtering and Sorting
  * Distance Units
 
* Users
  * Users
  * Creating a User Profile
  * Creating a Sign Up Form
  * Embedding a Sign Up Form in a Page
  * Signing In a User Manually
  * Signing In a User Automatically after Sign Up
  * Logging Out an Authenticated User
  * Resetting Password of an Authenticated User
  * Accessing Authenticated User Data
  * Sharing Attributes Across Multiple Profiles

* Properties
  * Properties
  * User-Defined Properties
  * Custom Addresses
  * Custom Attachments
  * Custom Images
 
* Custom Model Types
  * Custom Model Types
  * Persisting Data With Customizations
  * Loading Related Models

To be continued.

Two more batches to go.

**Comment by szabosteve** [comment]
7th batch.

* Forms
  * Forms
  * Form Configuration
  * Form Rendering
  * Form Server-Side Processing
  * Flash Messages
  * Default Payload
  * Form Validation
  * Form Examples

* Authorization Policy
  * Authorization Policy
  * Adding an Authorization Policy
  * Associating an Authorization Policy with Form Configuration
  * Associating an Authorization Policy with a Page
  * Handling a Violated Authorization Policy
 
* APIs
  * Creating Items from an External API Call
  * Persisting Part of a Third-Party API Response
  * Sending a Binary File Using an API Call Notification

* Migrations
  * Migrating Data
 
* Data Import/Export
  * Data Import
  * Data Import: Files
  * Data Export
  * Data Update
  * Model Relations

One more to go.

TBC.

**Comment by szabosteve** [comment]
8th batch.

* Integration
  * Integrating Slack Using API Call Notifications
  * Integrating SendGrid Using API Call Notifications
  * Integrating Twilio Using API Call Notifications
  * Adding reCaptcha Spam Protection

* QA
  * Testing
  * TestCafe
  * Installing TestCafe
  * Writing a TestCafe Test
  * Using the Page Object Model with TestCafe
  * Creating Marketplace Kit Logs
  * Developing GraphQL Queries Using marketplace-kit gui

* Payments
  * Integrating Stripe
  * Processing Payments with GraphQL Mutations

* Performance
  * Profiling Slow Pages
  * Measuring Execution Time of Liquid Code Fragments (time_diff)
  * Cache

* Activity Feeds
  * Activity Feeds
  * Implementing Activity Feeds

* GDPR
  * GDPR Compliance in platformOS

* Translations
  * Translations
  * Multi-Language Page
  * Translations: System Messages

* Blog
  * Installing the Blog Module
  * Adding a Blog Post
  * Blog Settings and Posts

It is done! Thanks for the patience, it took longer than expected.
