### ISSUE TITLE
Implement spellcheck as continous integration step

### ISSUE THREAD

**Issue by pavelloz** [Platform-OS/platformos-documentation#334]
As it turns out we have a lot of typos etc. so maybe every-day spelling check (and in v2 on PR) would help to keep it down.

**Comment by diana-lakatos** [comment]
Most issues are with capitalization (e.g. sms or SMS) and spaces (removed from end of line). Couple of mistakes with commas and hyphenated words. 

Current solution: going through all existing topics with Grammarly, and editing any typos, capitalization issues, etc. All new topics are checked manually with Grammarly, so the number of issues should decrease after this initial phase. Still, automated spell check would be very welcome.

**Comment by pavelloz** [comment]
https://github.com/tbroadley/spellchecker-cli + retext-* plugins inside docker

`spellchecker -f 'marketplace_builder/views/pages/**/*.liquid' --no-suggestions -d dictionary.txt -q -p assuming`
