### ISSUE TITLE
Generate navigation

### ISSUE THREAD

**Issue by diana-lakatos** [Platform-OS/platformos-documentation#338]
Consider generating the navigation based on page metadata and slug, find solution for ordering section and topic titles.

**Comment by pavelloz** [comment]
@mdyd-dev/production any suggestions to avoid perf. issues?

There is css class on one item in the menu, indicating active item, so static caching is not an option without js magic, thats why we are looking at generating the menu using gql and metadata.

**Comment by pavelloz** [comment]
Decided that it will create more issues than solve ATM.

Lets revisit if the issue of forgetting things bite us again.
