### ISSUE TITLE
Explain priority in more detail in Narrowing Keyword Search topic

### ISSUE THREAD

**Issue by diana-lakatos** [Platform-OS/platformos-documentation#340]
Explain this more (/tutorials/search/narrowing-keyword-search):

Priority

While defining which fields should be traversed in keyword search you can also force the priority of each field to make sure they will appear in results higher (they will have higher `score`).

//: <> TODO: Explain better. This is basically abstraction on top of `boost` property in ElasticSearch

//: <> ### Example//: <> TODO

**Comment by pavelloz** [comment]
And migrate examples to `models` from `people` endpoint

**Comment by Slashek** [comment]
page doesn't exist anymore

**Comment by pavelloz** [comment]
Yes it does

https://documentation.platformos.com/developer-guide/search/narrowing-keyword-search

**Comment by Slashek** [comment]
yeah but that's for deprecated people/customizations. We are looking into adding keyword search to models/users
