### ISSUE TITLE
Write error messages reference

### ISSUE THREAD

**Issue by diana-lakatos** [Platform-OS/platformos-documentation#341]
List of error messages, meaning, fixes

**Comment by pavelloz** [comment]
Error messages from where?

**Comment by diana-lakatos** [comment]
Where users can bump into error messages, e.g. Marketplace Kit.

**Comment by pavelloz** [comment]
Ouh yeah, i was thinking about it for a long long time.
I think we need error codes

Example:

"Error 101 - Model name has to be unique. Read more: https://documentation.platformos.com/errors#101"

And the link would be basically point to a list of all errors described on one page.

At least ive seen it in couple of places in the wild and it was always a nice touch. 

Usually link is very short (bit.ly or something) but i dont know if thats a must have. It has one huge advantage though - link underneath can be updated, so if we decide to change the url, we just update bit.ly and everyone having the old link still has perfectly good url.

**Comment by diana-lakatos** [comment]
This is a duplicate, I copied all information to the main ticket.
