### ISSUE TITLE
Write tutorial for Deleting a User

### ISSUE THREAD

**Issue by diana-lakatos** [Platform-OS/platformos-documentation#344]
Deleting a User tutorial for the Tutorials/Users section.

**Comment by diana-lakatos** [comment]
Why there's no hard delete?
Ways to soft delete a user
Are users eventually completely deleted? If so, how long does that process take?
What if a user is "deleted" and their email is used to create a new user?

Notes:
Using Deleted_at allows the Front End Dev to use a Mutation to later 'undelete' if done within a time-frame of 30 days (but actually it's more like 90 days at the moment).
It removes a lot of support headaches for everyone - especially if a user has accidentally deleted data, in spite of X warnings that a FED might have placed in the UI confirmation.

**Comment by diana-lakatos** [comment]
Using Deleted_at allows the Front End Dev to use a Mutation to later 'undelete' if done within a time-frame of 30 days (but actually it's more like 90 days at the moment).
It removes a lot of support headaches for everyone - especially if a user has accidentally deleted data, in spite of X warnings that a FED might have placed in the UI confirmation.

**Comment by pavelloz** [comment]
I think this is covered in https://documentation.platformos.com/developer-guide/models/data-backup-removal

**Comment by diana-lakatos** [comment]
Yes, thank you!
