### ISSUE TITLE
Write use case about development workflow

### ISSUE THREAD

**Issue by diana-lakatos** [Platform-OS/platformos-documentation#345]
Use case should describe the tools and processes a our team uses to collaborate on Instances.
Requested in this Town Hall: https://www.youtube.com/watch?v=T2Ovm6v88hI

**Comment by diana-lakatos** [comment]
Partially addressed in Testing and QA Best Practices article series, and related to this issue #477

**Comment by pavelloz** [comment]
I think @godot has something cooked up as an image to help kickstart it :)

**Comment by godot** [comment]
![image](https://user-images.githubusercontent.com/150861/59771027-45d18c80-92a9-11e9-8120-f05b491c7ccd.png)

**Comment by diana-lakatos** [comment]
Note: this should be either a Best Practice or an update to https://documentation.platformos.com/how-platformos-works/platformos-workflow/development-workflow

**Comment by diana-lakatos** [comment]
![development_workflow](https://user-images.githubusercontent.com/4191691/73518010-77910100-43fd-11ea-822e-415aec908650.png)

**Comment by pavelloz** [comment]
Arrow heads are barely visible, and they are very important ;)

**Comment by diana-lakatos** [comment]
Thank you! We updated the image with more visible arrow heads. 

![development_workflow2](https://user-images.githubusercontent.com/4191691/73543134-9495f600-4436-11ea-9a1c-6a602e2af793.png)

**Comment by Developer-DNM** [comment]
Looking great!

**Comment by diana-lakatos** [comment]
Thank you! It's up on the documentation site: https://documentation.platformos.com/how-platformos-works/platformos-workflow/development-workflow
