### ISSUE TITLE
Group tutorials by topic

### ISSUE THREAD

**Issue by diana-lakatos** [Platform-OS/platformos-documentation#348]
Problem: There are too many tutorial topics in the left menu, we should find a way to group / order / sort them to make them easier to find.

**Comment by pavelloz** [comment]
Agree.

And we probably should start tagging articles somehow with difficulty in mind, because sometimes its just too hard to jump into an article straight in the begining.

**Comment by diana-lakatos** [comment]
**Update:** We have discussed an approach with Pawel and Kata to categorize tutorials.

This approach would aim to **create larger categories** (non-collapsible in our case!) to organize the current categories visually, similarly to Stripe’s API docs: https://stripe.com/docs/api/coupons/update. The topic _“Update a coupon”_ is under _Coupons_, which is under _BILLING_.
In our case, it could be something like this: the topic _“Uploading Files Directly to Amazon S3 Using AJAX”_ would be under _User Uploads_, which would be under _FILE MANAGEMENT_.

We will use an **online card sorting tool** to identify the most intuitive structure where pOS team members and Partners can share their thoughts. 

The **navigation will be hard-coded HTML** to allow for maximum freedom without complexity.

**Comment by pavelloz** [comment]
Looks like its done @diana-lakatos ;)
