### ISSUE TITLE
Write topic on Form Lifecycle

### ISSUE THREAD

**Issue by diana-lakatos** [Platform-OS/platformos-documentation#352]
From ChrisD: 
Accessing form data in different parts of the form. To give more context, depending on where you are it’s either:

- `params.properties_attributes.foo` (although variable is `form[properties_attributes][foo]` so it should be `params.form.properties_attributes.foo`
- `form_builder.fields.properties.foo.value`
- `form.foo` (notice that there is no `properties` here)

I believe we need a general article on form lifecycle. That’s a term taken from React, where the lifecycle method are the integral part of the library. Take a look at this image:
https://cdn-images-1.medium.com/max/2000/1*cEWErpe-oY-_S1dOaT1NtA.jpeg 

Without going into much detail, it gives you a clear indication when certain methods are run (think default_payload processing, redirect_to, callbacks) and what data is available.

**Comment by pavelloz** [comment]
I believe most of the work has been done here: https://documentation-staging.staging.oregon.platform-os.com/tutorials/forms/form-server-side-processing

**Comment by diana-lakatos** [comment]
Task: verify if everything was addressed from the original task. Thank you!

**Comment by pavelloz** [comment]
?

**Comment by Slashek** [comment]
https://documentation.platformos.com/developer-guide/forms/form-server-side-processing
