### ISSUE TITLE
Extend GraphQL Mutations

### ISSUE THREAD

**Issue by diana-lakatos** [Platform-OS/platformos-documentation#353]
Feedback through docs site feedback block:
Message: It'd be nice if it went into more detail. It felt like this page was just a stub.
Feedback to: https://documentation.platform-os.com/api-reference/graphql/g/operation/mutation

**Comment by pavelloz** [comment]
New page url: https://documentation-staging.staging.oregon.platform-os.com/api-reference/graphql/mutations

(content is mostly the same)

**Comment by pavelloz** [comment]
Or newer, better version: https://documentation-staging.staging.oregon.platform-os.com/api-reference/graphql/rootmutation.html
