### ISSUE TITLE
Write e-commerce use case 

### ISSUE THREAD

**Issue by diana-lakatos** [Platform-OS/platformos-documentation#356]
So far we have:

- E-commerce in platformOS
- Setting up the Instance
- Configuring the Data Schema
- Building the Admin Section
- Using Shared Partials
- Seeding Configuration Data
- Creating Product Management Forms
- Adding Photos to Products

**Comment by pavelloz** [comment]
Done? https://documentation.platformos.com/use-cases/e-commerce/e-commerce-platformos

**Comment by diana-lakatos** [comment]
Not yet finished, @chrisdanek is the author.
