### ISSUE TITLE
Document generating PDFs from liquid

### ISSUE THREAD

**Issue by pavelloz** [Platform-OS/platformos-documentation#362]
> just wondering if PlatformOS had any HTML > PDF functionality (ie providing ability to users to download PDF versions of dynamically generated data, also possibly emailing PDF attachments generated by PlatformOS ).

**Comment by diana-lakatos** [comment]
Duplicate of #491 ?

**Comment by pavelloz** [comment]
Yes, this is the same feature, ill copy over this description to there so it wont disappear, because it touches on attaching to email as well.
