### ISSUE TITLE
Update Custom Attachments with declare

### ISSUE THREAD

**Issue by diana-lakatos** [Platform-OS/platformos-documentation#380]
Feedback to: 
https://documentation.platform-os.com/tutorials/properties/custom-attachments

Feedback: 
How about the declare attachment in html? after submit the form. thanks

From: 
donnie@cbo.me

**Comment by donnie24** [comment]
We have a form named `Incomplete Requirements Form` that should send an email message with the attachments the customer attached. Upon checking on the back end, the attachments are already saved in s3. I use the custom attachments for file upload.

*Issue*:
When the email message is sent, there are no attachments attached or included in it. I have tried different approaches, but I still cannot attach them.
https://cbo.d.pr/rS6EGd 

Here saving data https://cbo.d.pr/wRm5Ap

**Comment by pavelloz** [comment]
After slack discussion, closing in favor of: 
https://github.com/mdyd-dev/nearme-documentation/issues/384
