### ISSUE TITLE
Unify structure of official and custom pOS Liquid tags

### ISSUE THREAD

**Issue by diana-lakatos** [Platform-OS/platformos-documentation#405]
Make the structure for the documentation of official Liquid filters (https://documentation.platform-os.com/api-reference/liquid/filters) and pOS-specific Liquid filters (https://documentation.platform-os.com/api-reference/liquid/platformos-filters) the same.

**Comment by diana-lakatos** [comment]
_Proposed structure shown through an example pOS Liquid filter:_

## is_included_in_array

Returns a Boolean based on whether the array includes the element. 

### Parameters

```liquid
{{ array | is_included_in_array: 'el' }}
```

* **array** (Array): the array of elements to find the specified element in
* **el** (Object): the element you look for in the array 

### Examples

#### Input

```liquid
{% assign elements = 'a,b,c,d' | split: ',' %}
{{ elements | is_included_in_array: 'c' }}
```

#### Output

```liquid
true
```

**Comment by diana-lakatos** [comment]
This task comes before #363

**Comment by diana-lakatos** [comment]
Change of plans: this task comes later, #363 will be done separately

**Comment by pavelloz** [comment]
<img width="698" alt="image" src="https://user-images.githubusercontent.com/546845/59016974-c7093800-8842-11e9-880e-cdfc4ac03012.png">
^ This might not be possible in autogenerated docs. Im not sure - @piotrze

**Comment by Nagygyorgy** [comment]
**User feedback**
On our documentation site, there is a separation between platformOS related and original liquid tags and filters. It makes hard for users to find the right tag with these separations. It was also mentioned that it's hard to spot the relationship between the categories. 

Suggestion: It would be great to merge the filters under one menu item and add a pOS tag next to the platformOS specific filters. In this case, it shows the contribution to liquid and at the same time, the user finds them in one place. 

Same goes for tags. The only difference is that hey can land in the related menu category.

**Comment by pavelloz** [comment]
Things to think through:
1) There is 113 filters in total.
71 pos
41 built in

Table of content for each of them is longer than the big screen already. Navigating in it might become very annoying for everybody.

2) Separation was made also to not mislead people who come to us for liquid docs, not for pOS docs.

**Comment by Slashek** [comment]
we have improved this section recently, we can create a new card if needed
