### ISSUE TITLE
Add example to Feeding Data into AMP Pages with GraphQL

### ISSUE THREAD

**Issue by diana-lakatos** [Platform-OS/platformos-documentation#421]
https://documentation.platform-os.com/tutorials/amp/feeding-data-amp-pages-graphql

As discussed in this PR: #406

**Comment by pavelloz** [comment]
Feeding data to amp pages is the same as feeding data into any other page, no reason to make a specific article, we have articles on models and graphql

**Comment by diana-lakatos** [comment]
We don't need to write a new article, this ticket was created because the topic is missing the source code section: https://documentation.platformos.com/best-practices/amp/feeding-data-amp-pages-graphql
