### ISSUE TITLE
Describe all Partner Portal flags that change instance behavior

### ISSUE THREAD

**Issue by pavelloz** [Platform-OS/platformos-documentation#438]
Information should include:

* description
* default value
* possible values

Flags:

* test_mode
* test_email
* maintenance_mode
* include_tag_with_private_scope
* skip_action_types_and_pricings
* enable_sms_and_api_workflow_alerts_on_staging

**Comment by Slashek** [comment]
skip deprecated `skip_action_types_and_pricings`, `test_mode`

**Comment by pavelloz** [comment]
Well, lets describe it as "deprecated", since they appear in PP and users see them
