### ISSUE TITLE
Default payload example and documentation doesnt work

### ISSUE THREAD

**Issue by pavelloz** [Platform-OS/platformos-documentation#467]
In both cases:

https://github.com/mdyd-dev/nearme-documentation/blob/master/marketplace_builder/views/pages/tutorials/forms/form-rendering.liquid#L22

https://github.com/mdyd-dev/nearme-documentation/blob/master/marketplace_builder/views/pages/tutorials/forms/form-configuration.liquid#L64

This line does nothing, because default payload is not working.

Can be verified in example repo as well:

* https://examples.platform-os.com/full-form-example
* https://github.com/mdyd-dev/marketplace-nearme-example/blob/38f8fcc0faf98c97e343289c8ff377c213d0d47b/modules/full_form/public/form_configurations/full_form_example.liquid#L32-L39

**Comment by Slashek** [comment]
please note: `form_builder` has been shortened to `form`

**Comment by lemingos** [comment]
@pavelloz this example works just fine. Please submit the form so it raise the validation. Property value is set in when processing submit request and displayed on validation handling page.

**Comment by pavelloz** [comment]
@lemingos can you add test for things mentioned in the documentation article? there are examples of tests in modules next to it

cc @jnorbert

**Comment by lemingos** [comment]
Yes.

**Comment by pavelloz** [comment]
TY :)

**Comment by lemingos** [comment]
https://github.com/mdyd-dev/marketplace-nearme-example/pull/57 added test here
