### ISSUE TITLE
Improve onboarding docs

### ISSUE THREAD

**Issue by diana-lakatos** [Platform-OS/platformos-documentation#479]
Collect feedback on the onboarding docs (Get Started, Quickstart Guide), and improve them based on the feedback.

**Comment by diana-lakatos** [comment]
Idea: Get Started should show a whole scenario (to-do application) from start to finish, including information and tips on development workflow, QA, etc.

**Comment by diana-lakatos** [comment]
Onboarding Journeys:

- Non-technical: 1-Click Install (demo site + blog module)
- Semi-technical: Sandbox/Hello World
- Technical: Build Your Own Blog Module

**Comment by diana-lakatos** [comment]
Documentation task list from the Onboarding Roadmap

- [X] UI copy and instructions for onboarding screens 
- [X] Hello World planning and outline 
- [X] Hello World documentation
- [ ] `on hold until development done` Hello World video 
- [X] Build Your Own Blog planning and outline 
- [X] ToDo List App outline
- [x] ToDo List App documentation
- [ ] ToDo List App videos

**Comment by Slashek** [comment]
let's create a new card if needed
