### ISSUE TITLE
Extend GraphQL editor documentation

### ISSUE THREAD

**Issue by diana-lakatos** [Platform-OS/platformos-documentation#485]
The GraphQL editor has its own reference documentation, but it's not complete, and it doesn't include tutorials. We could: 
- extend editor's docs
- write about how to use the editor's docs
- add tutorials

**Comment by pavelloz** [comment]
Documentation on how to use documentation?

**Comment by diana-lakatos** [comment]
More like tips on how to use it most effectively.

**Comment by pavelloz** [comment]
done

https://documentation.platformos.com/developer-guide/graphql/developing-graphql-queries-using-pos-cli-gui
