### ISSUE TITLE
Tutorial about PDF generation

### ISSUE THREAD

**Issue by diana-lakatos** [Platform-OS/platformos-documentation#491]
Requested by Shane/CBO

**Comment by ignacy** [comment]
@diana-lakatos I'm affraid I'll not be able to write more about this topic. After reminding myself where we stand I don't have much to add over what's already here:

https://documentation.platform-os.com/tutorials/pages/pages

In particular, if you want a PDF you create a regular page and you just request it in PDF format as described in [Accessing Different Formats](https://documentation.platform-os.com/tutorials/pages/pages#accessing-different-formats) section.

The implementation we have right now is very basic and I know there are porblems with it (links to images don't work, images have to be placed right in Page body encoded in base64 format, performance is not so great, ..) 

I know that @pavelloz (is | will be) working on a better solution for rendering PDF views. I think we should focus on it, as what we have right now is not that great.

**Comment by diana-lakatos** [comment]
@ignacy Thank you! I will follow up with @pavelloz.

**Comment by pavelloz** [comment]
Code is ready, but its not plugged into the stack yet. No ETAs on that.

@Slashek

**Comment by diana-lakatos** [comment]
@Slashek Any news on PDF generation updates? We should update docs accordingly and write a tutorial, if the feature is ready.

**Comment by pavelloz** [comment]
Should include attaching pdf to emails per https://github.com/mdyd-dev/nearme-documentation/issues/362

**Comment by Nagygyorgy** [comment]
Related example: https://examples.platform-os.com/pdf-generation

**Comment by pavelloz** [comment]
Will be handled in here: https://github.com/mdyd-dev/nearme-documentation/issues/783
