### ISSUE TITLE
Update sitemap documentation page

### ISSUE THREAD

**Issue by diana-lakatos** [Platform-OS/platformos-documentation#492]
Tasks: 

- update the sitemap doc page with information about robots.txt
- example of Auto generated robots.txt that a CP can use GraphQL to create

**Comment by pavelloz** [comment]
Auto generated robots.txt? Anybody does that?

**Comment by Slashek** [comment]
we automatically take care of duplicated content now

**Comment by Slashek** [comment]
btw - https://documentation.platformos.com/best-practices/seo/creating-dynamic-sitemap#content
