### ISSUE TITLE
Update of 404 page

### ISSUE THREAD

**Issue by jnorbert** [Platform-OS/platformos-documentation#498]
Actual result:
https://take.ms/DDrUF

I think we could implement something more user friendly.

**Comment by pavelloz** [comment]
Current progress:
![image](https://user-images.githubusercontent.com/546845/60106330-51b7c580-9765-11e9-9d5a-509fe73cffc1.png)

Soon it will exclude most conditional blocks (feedback, breadcrumbs) but its still much better than it was so i deployed it to prod as it is for now.

**Comment by pavelloz** [comment]
Preview: https://documentation.platformos.com/doesnt-exist

**Comment by pavelloz** [comment]
Closing, any feedback will be done in new issue ;)
