### ISSUE TITLE
Liquid error on the how-to-contribute page

### ISSUE THREAD

**Issue by jnorbert** [Platform-OS/platformos-documentation#521]
URL: https://documentation.staging.oregon.platform-os.com/community/how-to-contribute

Actual result:
http://take.ms/cRzs3

**Comment by pavelloz** [comment]
So far commented out - when time allows, need to fix gql tag inside for loop.

**Comment by ghost** [comment]
Created PR here: https://github.com/mdyd-dev/nearme-documentation/pull/551

**Comment by ghost** [comment]
@diana-lakatos Looks like you've tried in production? In production the backend part with enabling GraphQL inside for loops hasn't yet been deployed.

**Comment by ghost** [comment]
Also, another change/fix has been added to the frontend repository.

**Comment by diana-lakatos** [comment]
@andrei Yes, I checked it on production. All working fine now, I'm closing this issue. Thank you!
