### ISSUE TITLE
Deprecate remote-docs for hardcoded version

### ISSUE THREAD

**Issue by Slashek** [Platform-OS/platformos-documentation#523]
If you wanted to quickly search info regarding something in graphql, you can't

**Comment by pavelloz** [comment]
It ignores all remote docs (pulled by xhr).

If we want to search through it we need to:
* cache JSONs in db
* adjust search to mix search from static pages + models
* rewrite views from js to liquid

**Comment by pavelloz** [comment]
Decided to just hardcode after redesign.

**Comment by pavelloz** [comment]
Done.
