### ISSUE TITLE
Update Validations topic

### ISSUE THREAD

**Issue by diana-lakatos** [Platform-OS/platformos-documentation#528]
Feedback on: 
https://documentation.platform-os.com/tutorials/forms/validation

Feedback:
Missing descriptions for some validation options. For instance, "unique". Is it unique across records, or is it unique compared to another field in the same form submission?

**Comment by pavelloz** [comment]
Assigned issues are very rarely touched, unassigned are never toched.

**Comment by diana-lakatos** [comment]
@Slashek Please advise who could do this task. Thanks!

**Comment by Slashek** [comment]
the old link does not work, the new one is https://documentation.platformos.com/developer-guide/forms/validation#content which is much more descriptive
