### ISSUE TITLE
incomplete liquid whitespace control docs

### ISSUE THREAD

**Issue by onecreative** [Platform-OS/platformos-documentation#530]
The docs teach that whitespace can be controlled by using a dash on each side of the tag (`{{- var -}}`). However, this is only part of the functionality. A dash on the left removes whitespace on the left, while a dash on the right removes whitespace on the right.

This matters because a developer might figure out that they only need a dash on one side or the other for their particular scenario, but they might not realize that the single dash is actually changing the behavior in other ways.

I can't find the docs where I learned this, so I can't provide a reference. Sorry!

**Comment by pavelloz** [comment]
Have you seen this: https://documentation.platform-os.com/api-reference/liquid/whitespace-control
?

If yes, intro needs rewording + examples

**Comment by onecreative** [comment]
I'll try to find where I learned about the different options for whitespace control. Maybe Scott Reynolds remembers.

**Comment by onecreative** [comment]
@pavelloz It mentions it here: https://help.shopify.com/en/themes/liquid/basics/whitespace

**Comment by onecreative** [comment]
So, I'm now seeing the subtle wording in the first paragraph, where it says: 

> to strip whitespace from the left `or` right side of a rendered tag.

So, like you said, we just need to expand on it with a better description and some examples.
