### ISSUE TITLE
Update Stripe integration tutorial for new Payment module

### ISSUE THREAD

**Issue by diana-lakatos** [Platform-OS/platformos-documentation#533]
Tutorial is for our old hardcoded and limited integration with stripe, which wouldn’t help much with storing payments, displaying those payments etc. Our official way of integrating stripe would be through module https://github.com/mdyd-dev/platformos-payments which in Readme explains how it works; we actually use it for our Partner Portal to handle billing via microservice implemented in platform os

**Comment by pavelloz** [comment]
cc @lemingos
