### ISSUE TITLE
duplicate Liquid `compact` filter in docs

### ISSUE THREAD

**Issue by onecreative** [Platform-OS/platformos-documentation#534]
The liquid docs show the `compact` filter in both the standard liquid filters and the custom pOS filters. Which is it? If it's both, then we probably need a note by each one stating that it exists in Liquid already, but that we have improved it in such and such ways.

**Comment by onecreative** [comment]
The same scenario exists for `new_line_to_br`.

**Comment by pavelloz** [comment]
@Slashek can we get rid of our compact?

**Comment by Slashek** [comment]
our compact handles also blank elements, like empty strings or empty arrays/hashes. the other day I've improved it to be a proper drop-in replacement for the built-in one
