### ISSUE TITLE
Deprecate Liquid filter, "fetch"

### ISSUE THREAD

**Issue by onecreative** [Platform-OS/platformos-documentation#535]
`fetch` does the same thing as `dig`, except that it doesn't do nested values like `dig` does. I suggest deprecating this filter.

And on the note of deprecating, I think it would be a good idea to have a `deprecated` tag and notes to explain why.

This probably should be two separate issues, but I'm lazy.

**Comment by pavelloz** [comment]
@Slashek 

I think we should deprecate fetch, as dig has more safety checks.

**Comment by Slashek** [comment]
deprecated fetch

**Comment by diana-lakatos** [comment]
@pavelloz Please remove it from the documentation (or mark as deprecated and add what to use instead): https://documentation.platformos.com/api-reference/liquid/platformos-filters#fetch
Thank you!
