### ISSUE TITLE
"humanize" liquid filter assumes coding standards

### ISSUE THREAD

**Issue by onecreative** [Platform-OS/platformos-documentation#536]
I'm not against the `humanize` filter necessarily. It's not a high value filter, but I can see where it would be useful. But that usefulness becomes limited when a dev with different coding standards is trying to use it. For instance, it translates `company_id` to `Company`, but that assumes the dev uses underscores to separate words and labels IDs in a similar manner.

I think if we are going to have filters that make assumptions like this, then we should also have it do at least one of the following:

1. reference a best practices section of the docs that lists out coding standards. 
1. list out the specific things that the filter does

**Comment by pavelloz** [comment]
Someone forwarded it from our framework for whatever reason and here we are. 

Its so obscure its not worth the time, especially if it would break someones code.
