### ISSUE TITLE
Redundant liquid filters: "any" vs "is_included_in_array"

### ISSUE THREAD

**Issue by onecreative** [Platform-OS/platformos-documentation#538]
These filters appear to do the same thing. Is one superior to the other? Perhaps we can deprecate one or make one an alias of the other?

**Comment by pavelloz** [comment]
@Slashek 
Yes, seems like a duplication.

**Comment by Slashek** [comment]
PR with deprecation created

**Comment by diana-lakatos** [comment]
Is one of them deprecated? They are both still in the documentation:
https://documentation.platformos.com/api-reference/liquid/platformos-filters#any
https://documentation.platformos.com/api-reference/liquid/platformos-filters#is_included_in_array

@pavelloz Please update the documentation if the deprecation is done. Thanks!
