### ISSUE TITLE
"newline_to_br" vs "new_line_to_br"

### ISSUE THREAD

**Issue by onecreative** [Platform-OS/platformos-documentation#540]
These appear redundant. Is the pOS filter superior? If so, can we rename it to replace the existing one?

**Comment by pavelloz** [comment]
It looks like they do the same thing. Should be possible to alias one to another, especially that we already have also `nl2br` for some reason.

@Slashek

**Comment by Slashek** [comment]
deprecated our custom filters, the built-in is fine

**Comment by diana-lakatos** [comment]
This is at the end of our docs page: https://documentation.platformos.com/api-reference/liquid/platformos-filters#new_line_to_br-aliases-nl2br

I'm not sure it's clear that this is deprecated, along with the other filters that are deprecated and are added at the end of the list:

![Screenshot 2020-07-16 at 7 35 05](https://user-images.githubusercontent.com/4191691/87631076-eb6a6000-c736-11ea-8991-5b8e54af8fa5.jpg)

@pavelloz Could you please update? Thanks!
