### ISSUE TITLE
"slugify" vs "parameterize"

### ISSUE THREAD

**Issue by onecreative** [Platform-OS/platformos-documentation#541]
These the same thing? Is one superior? Should there be an alias?

**Comment by pavelloz** [comment]
Looking at examples, they give different results, so they cannot be aliased, or removed (breaking change). Additionally parameterize is customizable.

https://documentation.platformos.com/api-reference/liquid/platformos-filters#parameterize
https://documentation.platformos.com/api-reference/liquid/platformos-filters#slugify
