### ISSUE TITLE
Update Creating SEO-friendly URLs tutorial

### ISSUE THREAD

**Issue by diana-lakatos** [Platform-OS/platformos-documentation#552]
Feedback on: 
https://documentation.platform-os.com/tutorials/seo/creating-seo-friendly-urls 

Feedback: 
Doesn't answer questions about what you can and can't do. For instance, can you do /catalogue/{country}/cities/{city}?

**Comment by pavelloz** [comment]
I dont understand.

I think we should close tickets that are that old and noone has any idea what to do with them

**Comment by diana-lakatos** [comment]
I looked up the message, unfortunately, we didn't get an email address to get in touch with the user who sent it, so we can't ask what they meant.
