### ISSUE TITLE
Wrong URL to the example on the Processing Payments with GraphQL Mutations page

### ISSUE THREAD

**Issue by jnorbert** [Platform-OS/platformos-documentation#561]
URL: https://github.com/mdyd-dev/marketplace-nearme-example/tree/master/modules/payments/public/views/partials/payments/mutations.liquid

Screenshot:
https://take.ms/w0UoA

**Comment by lemingos** [comment]
Fixed in https://github.com/mdyd-dev/nearme-documentation/pull/591
