### ISSUE TITLE
Best Practices: dates, daylight saving times, locations 

### ISSUE THREAD

**Issue by diana-lakatos** [Platform-OS/platformos-documentation#562]
Best Practice article on setting time zone and setting daylight saving time: 
- geolocating user's location
- storing it in db
- asking user
- using `zone` 
- using date formats and translations
- using `localize`

**Comment by pavelloz** [comment]
Whats wrong with translations? https://documentation.platform-os.com/tutorials/translations/translations

**Comment by Slashek** [comment]
^ I believe the idea is how to use translations [ specifically date / time format ] to be able to display time/date in proper format depending on user's language, but also in proper time zone [ which might or might no be user's time zone; for example, if you buy airplane ticket you want to use airport's time zone etc ]

**Comment by Slashek** [comment]
closing as duplicate
