### ISSUE TITLE
Fine-tune feedback block design

### ISSUE THREAD

**Issue by diana-lakatos** [Platform-OS/platformos-documentation#566]
Adjust the feedback block design to look more like on the attached image. 

![feedback block](https://user-images.githubusercontent.com/4191691/59089073-8b857100-8909-11e9-8954-e0dd8c1d910c.png)

**Comment by pavelloz** [comment]
Done :)

I left the button on the left side, as its more recommended (in this book:  https://www.smashingmagazine.com/printed-books/form-design-patterns/ )  than overcomplicating without a reason.
