### ISSUE TITLE
Use case: How we solved remote docs issues

### ISSUE THREAD

**Issue by pavelloz** [Platform-OS/platformos-documentation#586]
# Case study

## Problem / situation

* Content was not searchable
* It was rendered in the browser, so it was taking CPU (and time)
* Rendered HTML was not cached server-side
* It required javascript maintenance (templates and the solution)

## Challenges

* Cache invalidation
* Naming things

## Solution 

* `download_file` filter instead of AJAX in browser
* `cache` tag with `key: page-slug-context.version`
* templates converted from `ejs` to `liquid`
* `searchable: true`

## Results

* Much faster experience
* Less javascript to maintain
* Easier to understand and edit by others templates (liquid) 
* Content is searchable

## Author information

Paweł Kowalski, Frontend developer
Doing things at platformOS
Code: https://github.com/mdyd-dev/nearme-documentation/blob/master/marketplace_builder/views/pages/api-reference/liquid/platformos-filters.liquid
Live example: https://documentation.platformos.com/api-reference/liquid/filters#append

## Tags

Background jobs
Cache
Performance

**Comment by diana-lakatos** [comment]
I think it should be a use case. Sending you guidelines for writing pOS use cases, and we can decide based on that.

**Comment by pavelloz** [comment]
Moved to first post

**Comment by pavelloz** [comment]
Structurally it fits :)

**Comment by diana-lakatos** [comment]
https://documentation.platformos.com/use-cases/improving-ux-remote-documentation
