### ISSUE TITLE
Add information about data retention 

### ISSUE THREAD

**Issue by diana-lakatos** [Platform-OS/platformos-documentation#594]
- data retention policy for basic and enterprise plans
- soft delete
- answer to question: I understand the concept of the soft delete re customisation but what happens to the related image? For example, you can also upload an image directly to S3 without the need for a customisation, if you don't keep a record of the url, you won't be able to access it, but it seems like the image is still stored. Just curious as to the effect of accumulating images over time without the ability to manage/delete these.

**Comment by diana-lakatos** [comment]
Additional comments from @ignacy on information about soft/hard delete:

> the obvious choice would be to have it in query documentation - it at least should say if the default is to include or not the soft deleted records. I also took a look at the queries we have in our guides and it looks like sometimes we omit the deleted_at filter like here https://documentation.platformos.com/tutorials/models/loading-related-models#step-2-load-related-model-for-each-record-not-recommended although if someone would use this code he might be surprised with the result. I guess what really would be needed is an audit of every query and every place this affects :)

**Comment by pavelloz** [comment]
> I understand the concept of the soft delete re customisation but what happens to the related image? For example, you can also upload an image directly to S3 without the need for a customisation, if you don't keep a record of the url, you won't be able to access it, but it seems like the image is still stored. Just curious as to the effect of accumulating images over time without the ability to manage/delete these.

Nothing. Image just sits there. Currently storing it is cheaper than writing a reliable system to remove only whats used and it wont change very soon.

**Comment by pavelloz** [comment]
On models: https://documentation.platformos.com/developer-guide/models/data-backup-removal
