### ISSUE TITLE
Documentation on using Auth0

### ISSUE THREAD

**Issue by diana-lakatos** [Platform-OS/platformos-documentation#604]
Explain how to use Auth0 for projects and its recommended use for SSO between multiple instances etc. with less coding than starting from scratch.
Needed: documentation/tutorial/example on how a dev team can make use of this for a project, what type of login (lock.js, universal) it has and anything else to consider, especially for ux flows.

**Comment by slightly-askew** [comment]
CBO happy to be test pilots :)

**Comment by diana-lakatos** [comment]
https://documentation.platformos.com/tutorials/identity-providers/identity-providers
