### ISSUE TITLE
Update How platformOS Works links to subpages

### ISSUE THREAD

**Issue by diana-lakatos** [Platform-OS/platformos-documentation#608]
too much space between links with icons, convert to bulleted list

**Comment by pavelloz** [comment]
I tried to fix the spaces in there already and it looks like markdown is very stubborn when it comes to inserting unnecessary `br` in between. I can just convert it to html to force it.

**Comment by diana-lakatos** [comment]
Actually, since the redesign, we don't use these icons consistently, so I don't mind removing them.

**Comment by diana-lakatos** [comment]
https://documentation.platformos.com/how-platformos-works
