### ISSUE TITLE
Add Marketplace gui info to the Get Started guide

### ISSUE THREAD

**Issue by Nagygyorgy** [Platform-OS/platformos-documentation#613]
It could be Step 7 on the list.
Instructions from Maciek:
> Once you install marketplace-kit and its dependencies and invoke marketplace-kit init and make sure that sync and deploy work, you should be good to start development. Please note you can use marketplace-kit logs <env> to see errors and marktplace-kit gui serve <env> to launch GraphQL editor to quickly develop and test GraphQL queries, using features like built-in docs and autocompletion.

**Comment by Slashek** [comment]
this will be the part of a new structure for getting started
