### ISSUE TITLE
pos-cli sync system issue

### ISSUE THREAD

**Issue by lemingos** [Platform-OS/platformos-documentation#635]
I've recently installed pos-cli on new system and I've had an issue while trying to sync 

```platformos-community [community-react-stream●●] % pos-cli sync staging
[16:58:23] Enabling sync mode to: https://tomek-community.staging.oregon.platform-os.com/
internal/fs/watchers.js:173
    throw error;
    ^

Error: ENOSPC: System limit for number of file watchers reached, watch 'modules/community/node_modules/@babel/helper-regex'
    at FSWatcher.start (internal/fs/watchers.js:165:26)
    at Object.watch (fs.js:1258:11)
    at /usr/lib/node_modules/@platformos/pos-cli/node_modules/node-watch/lib/watch.js:340:22
    at hasNativeRecursive (/usr/lib/node_modules/@platformos/pos-cli/node_modules/node-watch/lib/has-native-recursive.js:61:12)
    at Watcher.watchDirectory (/usr/lib/node_modules/@platformos/pos-cli/node_modules/node-watch/lib/watch.js:329:3)
    at /usr/lib/node_modules/@platformos/pos-cli/node_modules/node-watch/lib/watch.js:355:14
    at /usr/lib/node_modules/@platformos/pos-cli/node_modules/node-watch/lib/watch.js:121:35
    at Array.forEach (<anonymous>)
    at /usr/lib/node_modules/@platformos/pos-cli/node_modules/node-watch/lib/watch.js:119:13
    at FSReqWrap.args [as oncomplete] (fs.js:140:20)

[16:58:23] Sync failed.
```

AFAIR I had the same issue on MAC OS, now on ubuntu. I guess we should include this somewhere in the documentation as well as the solution:

Here is one that worked well on ubuntu https://github.com/guard/listen/wiki/Increasing-the-amount-of-inotify-watchers#the-technical-details.

``` echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf```

**Comment by pavelloz** [comment]
or just switch from node-watch to something better ;)

**Comment by pavelloz** [comment]
[This](https://yarnpkg.com/en/package/glob-watcher) looks like a sensible alternative and it has support for globs using pretty fast glob implementation, so it might be even faster. 

Additionally, it supports "add" event, which i think is missing from node-watch.

**Comment by pavelloz** [comment]
mdyd-dev/pos-cli#243
