### ISSUE TITLE
Update: Assets/Images - deleting, managing images/uploads on the CDN

### ISSUE THREAD

**Issue by diana-lakatos** [Platform-OS/platformos-documentation#638]
Clarify how we do it, when and how are images deleted on the CDN.

Quote from Partner: 

> For me personally Ive spent a bit of time trying to get my head around how you would delete/manage images/uploads, given during testing all physical images still existed at the CDN url after the customization delete. In my experience, despite advising clients to upload optimised images, they often don't, and they also may upload 5 or 6 images for say a single header banner, before they finally decide. In my experience, once in client hands, a lot of images/uploads could potentially be added in a short period of time where often they think they are just replacing images etc. Its good to know this process or purging happens automatically.

**Comment by pavelloz** [comment]
Images are not deleted from storage or CDN and it wont be possible in the near future.

**Comment by pavelloz** [comment]
@diana-lakatos I dont know where to put it, feel free to include that information: At the moment there is no way to just remove remove assets/files from s3. If user wants only one header out of 6 be present on the server, he should name the file the same, this way it will be overridden.

**Comment by pavelloz** [comment]
This is done
