### ISSUE TITLE
Describe how to migrate from marketplace-kit to pos-cli

### ISSUE THREAD

**Issue by diana-lakatos** [Platform-OS/platformos-documentation#639]
Could be added to release note about pos-cli renaming (July 15, 2019)

**Comment by pavelloz** [comment]
When using local node installation

```
npm r -g @platform-os/marketplace-kit
npm i -g @platformos/pos-cli
```

When using global node installation

```
sudo npm r -g @platform-os/marketplace-kit
sudo npm i -g @platformos/pos-cli
```

From now on, use `pos-cli` instead of `marketplace-kit` command.

**Remember to update your deploy scripts**

**Comment by diana-lakatos** [comment]
Thank you, @pavelloz, I'm adding this to the release note.
