### ISSUE TITLE
Document error codes

### ISSUE THREAD

**Issue by diana-lakatos** [Platform-OS/platformos-documentation#640]

**Comment by pavelloz** [comment]
Is this a good moment to discuss/implement the error DB (with error codes) and possible causes/solutions?

**Comment by diana-lakatos** [comment]
Yes, I think it would be very helpful, because we regularly get questions about errors and error messages. cc @Nagygyorgy

**Comment by pavelloz** [comment]
I was thinking about something like that: https://docs.aws.amazon.com/AWSEC2/latest/APIReference/errors-overview.html

But divided into categories:

* pos-cli
* graphql
* liquid
* partners

... list is open. The main thing is to identify at least the area where to look for  if someone is reporting error that should not be there.

After second thought, codes might be bad for long term, but name for error is a good idea (ie. `DeployTimeout`), like AWS did - that way there will never be numbering problem etc.

**Comment by diana-lakatos** [comment]
Thank you, @pavelloz, I think this looks good. Based on what we've discussed so far, I think we should have a stand-alone page for error codes (or multiple pages by category), and the docs should include:

- error code/name: I agree with having error names, but I guess we will still have the standard error codes, e.g. 500. 
- short error message:  We should discuss if a message is needed that the user immediately gets without looking at the docs, or if the names will be self-explanatory enough cc @Nagygyorgy 
- description of the error: what went wrong and why
- help on how to recover from the error  

 I renamed the issue to reflect our approach of planning to document all errors.

**Comment by diana-lakatos** [comment]
@Nagygyorgy Please advise on UX best practices and let's work on a wireframe. Thank you!

**Comment by Nagygyorgy** [comment]
Created a wireframe with small modifications for this section of the screen: 
- Here we have a header which identifies that we are under the modules section and the two tables have separate titles which can identify what users can see in that table.
-  Module names link to module’s page
- Version number identifies the version of the module ([We already have a ticket for that.](https://github.com/mdyd-dev/partner-portal/issues/636) If you can’t include now that’s fine, we just need to keep in mind that it should be there soon.
- Info section, can share status, update and other important information like “Monthly subscription” I wouldn’t add the price separately to the table. 
- The reason buttons look confusing on the current screen that those are not in line. If the same actions are in line it's easier to identify what is available with a module. Color differentiation could also help.

<img width="812" alt="Screen Shot 2019-07-29 at 13 38 06" src="https://user-images.githubusercontent.com/3997812/62046184-95d83300-b207-11e9-8d4a-e849ce08c03d.png">

**Comment by Nagygyorgy** [comment]
To make a proper wireframe I'd like to ask some content to work with. @pavelloz @diana-lakatos.
It's enough if you can provide a few examples with the most common variations. Based on the preferred content we can easily identify what layout structure fits best with it.

For a UX point of view, if we can address the following three topics we can help users effectively: 

- What the problem was. - Problem description.
- Why it happened. - The reason behind, as specific information to the user task as possible.  
- How to solve it.  - Provide helpful troubleshooting information.

**Comment by pavelloz** [comment]
I think we want to do something like https://docs.aws.amazon.com/AWSEC2/latest/APIReference/errors-overview.html

Example:


## pos-cli errors

| Error | Description |
|---|---|
| BadToken | Application you are trying to alter does not recognize given token as write. Check if application URL is correct and if you are added with "write" in Partners Portal |
| ArchiveTooBig | Release archive cannot exceed 50 MB. Most likely your assets are not compressed. |

**Comment by diana-lakatos** [comment]
Duplicate of #341

**Comment by Nagygyorgy** [comment]
@pavelloz @Slashek @diana-lakatos 
We discussed the layout for the Error message tables with Diana for this ticket: https://github.com/mdyd-dev/nearme-documentation/issues/640
The table would contain:
1. column: Error name
2. column: Short error message on top with code letter type, and description with solution
Layout: 1/4 left side navigation; 3/4 table
<img width="1094" alt="Error Message table" src="https://user-images.githubusercontent.com/3997812/62857466-ff703b00-bcf7-11e9-85fb-ee452e82eaa6.png">

We are planning the navigation and the placement of the error messages. The question is where would you place the error messages on the doc site?
It's OK that we will link to these errors messages, but we still need to find the right place of them in the Information Architecture. 
How about adding each error separately under their section (pos-cli, graphql, liquid, partners etc)?

**Comment by diana-lakatos** [comment]
Adding information from duplicate ticket here:

> Example:
> 
>  "Error 101 - Model name has to be unique. Read more: https://documentation.platformos.com/errors#101"
> 
> And the link would be basically point to a list of all errors described on one page.
> 
> At least ive seen it in couple of places in the wild and it was always a nice touch.
> 
> Usually link is very short (bit.ly or something) but i dont know if thats a must have. It has one huge advantage though - link underneath can be updated, so if we decide to change the url, we just update bit.ly and everyone having the old link still has perfectly good url.

**Comment by diana-lakatos** [comment]
I found this very nice resource:

Errors in software are unavoidable. Users might click a link that turns out to be broken or they might perform an action only to be met with an unexpected outcome. When a user encounters a problem, it’s important to write error messages in a way that doesn’t alienate the user.

Here are a few tips on what makes a good error message:

- Provide explicit indication that something has gone wrong.
- Write like a human, not a robot.
- Don’t blame the user – be humble.
- Make the message short and meaningful.
- Include precise descriptions of exact problems.
- Offer constructive advice on how to fix the problem.

Related resources:

[Error Message Guidelines – Microsoft](https://docs.microsoft.com/en-us/windows/win32/debug/error-message-guidelines)
[Error Message Guidelines –- NN Group](https://www.nngroup.com/articles/error-message-guidelines/)
[How to Write Good Error Messages -– UX Planet](https://uxplanet.org/how-to-write-good-error-messages-858e4551cd4)
[How to write better error messages –- opensource.com](https://opensource.com/article/17/8/write-effective-error-messages)

**Comment by diana-lakatos** [comment]
We have improved our error messages.
