### ISSUE TITLE
Update Form documentation (input name)

### ISSUE THREAD

**Issue by diana-lakatos** [Platform-OS/platformos-documentation#641]
Add or highlight the following information in Form docs:

Add [] after the name to the input, so it will look like <input name=„{{... colors.name }}[]” ...>

**Comment by pavelloz** [comment]
Well, it's only true for arrays, so just slapping it in there will be wrong and wont fix the core issue of developer having to know when to use it and when to not use it.

It more of standard in areas of html, browsers and how servers process form data than platformOS specific.

**Comment by Slashek** [comment]
implemented proper fix - platformOS will now correctly add `[]` automatically for arrays
