### ISSUE TITLE
pos-cli require a higher version of node than 8

### ISSUE THREAD

**Issue by jnorbert** [Platform-OS/platformos-documentation#644]
URL: https://documentation.platformos.com/how-platformos-works/platformos-workflow/pos-cli

> pos-cli requires Node.js version 8 or higher to work properly.

Actual result:
https://take.ms/WJOI9

@pavelloz seems that pos-cli require a higher version of node than 8.

**Comment by pavelloz** [comment]
I'll update the docs to reflect the reality.
