### ISSUE TITLE
Add copyright page with attributions

### ISSUE THREAD

**Issue by diana-lakatos** [Platform-OS/platformos-documentation#651]
Link copyright in the footer to a page that describes how our documentation site it open-source and lists attributions to open-source elements we used (e.g. icons).

**Comment by diana-lakatos** [comment]
@pavelloz Please provide a list of attributions we need (for icons, etc.) and I will write the copy for this page.

**Comment by pavelloz** [comment]
https://www.flaticon.com/authors/dave-gandy
Dave Gandy
external link icon

https://www.flaticon.com/authors/google
Google
search icon 

https://www.flaticon.com/authors/freepik
Freepik
right arrow icon

from www.flaticon.com

---

This is what ive identified. 
A lot of icons i have no idea how we got. 
Archeology is too time consuming and error-prone for me to guess.
