### ISSUE TITLE
Add visible indicator to doc updates

### ISSUE THREAD

**Issue by diana-lakatos** [Platform-OS/platformos-documentation#659]
a visible indicator when sections of the documentation have "updated contents", something like the screenshot which could last for 1 week upon publishing of changes.
(design should be discussed)

![updated_topic](https://user-images.githubusercontent.com/4191691/61448446-32bae680-a953-11e9-9c62-0ea1842f353a.png)

**Comment by pavelloz** [comment]
Hmm, categories are not updated, only pages have `updated_at` timestamp, but with a little bit of css/javascript i think it might be possible to automate it.

Meaning: If any article below (inside page and layouts) has been updated in less than X days, display NEW next to the "Page and layouts".

Im not sure if this wont cause whole nav to light up green but we can try :)

**Comment by diana-lakatos** [comment]
I think it makes sense to do it on the page (topic) level, marking categories that have new or updated topics helps, and then when users click on the category, they can see which topic has been added.

**Comment by pavelloz** [comment]
![image](https://user-images.githubusercontent.com/546845/61465148-c9010380-a977-11e9-9483-27713ed73101.png)

Lets base on that screenshot - this is a more realistic use case.

Assuming Metadata and Layouts pages changed, what should happen?

**Comment by diana-lakatos** [comment]
We discussed this with @Nagygyorgy, this would be the best approach if it's feasible: let's display `New!` next to the categories of updated topics when they are closed, so that users can immediately see where there was a change — this helps discovery. Then, when the user opens the category, the `New!` next to the category should disappear, and `New!` next to the updated topics should be displayed. 

So on the screenshot: `New!` should be displayed next to Pages and Layouts when it's closed, and next to Metadata and Layouts after the category has been opened.  

Design:
Similarly like on the screenshot, written like this: `New!`. It should be in a smaller font than the topic or category, and should be this green color: #45A041

**Comment by Nagygyorgy** [comment]
<img width="478" alt="Sidebar_update" src="https://user-images.githubusercontent.com/3997812/61526163-2e0d3580-aa1a-11e9-8db6-73daad406c37.png">

**Comment by pavelloz** [comment]
I **think** it is possible ;)

It will complicate a little bit nav code, but let's hope not too much. I have some ideas on how to approach this.

**Comment by pavelloz** [comment]
<img width="315" alt="image" src="https://user-images.githubusercontent.com/546845/61714755-f70d8b80-ad5b-11e9-81dd-4544ed1ba7b4.png">
<img width="294" alt="image" src="https://user-images.githubusercontent.com/546845/61714793-0987c500-ad5c-11e9-8c76-0960945db6f3.png">


Looks like its going to be possible with not much complexity added
