### ISSUE TITLE
The search engine does not work as expected

### ISSUE THREAD

**Issue by jnorbert** [Platform-OS/platformos-documentation#698]
@diana-lakatos in our team we noticed that the search does not return the expected results. 
We decided to add this task as an introduction to the discussion on how or using which engine the search engine should be implemented. I think the best way for it is a discussion with Maciek and Paweł.

Example of issues:
https://take.ms/Aloqa

**Comment by diana-lakatos** [comment]
Thank you @jnorbert! I think this might be a duplicate of #576, or at least you can use the idea added there as a starting point.

**Comment by jnorbert** [comment]
Thanks @diana-lakatos indeed looks like a duplicate.

**Comment by pavelloz** [comment]
I closed #576 after deeper research.

Our options are: 
* internal improvement
* using algolia - its free for open source projects and the best in the biz (see searches at https://tailwindcss.com/ & https://webpack.js.org/ )

**Comment by diana-lakatos** [comment]
We have also discussed to investigate using ElasticSearch.
