### ISSUE TITLE
Update Search topics

### ISSUE THREAD

**Issue by diana-lakatos** [Platform-OS/platformos-documentation#708]
https://documentation.platformos.com/tutorials/search/search

- [ ] search through `customization` is the only thing that is left from the
   `customization` field, everywhere else we use `model` this is not stated
   anywhere but it matters as it's confusing why you use one set of fields here
   and elsewhere something different

- [ ]  Here we mention `listings` query https://documentation.platformos.com/tutorials/search/creating-search-query
   I guess we should move to `modules` everywhere but this example would have to
   be completely rewriten

- [ ] Based on "Search" tutorial, let's say you would want to find items which
   price is between some values, like items with price between 10 and 20
   dollars.. I'm not asking how would you do it but could you guess which page
   has this kind of stuff?

- [ ] The whole layout is a bit disorienting when I use it. I'd prefer to have it
   as single search page where I could Ctrl+F search it from my browser. The
   reason for that is that after using platform you kind know what you look
   for.. like I know I need to find `query` parameter if I had it all on one
   page it would be easy for me to find. If we have sections I'd prefer if that
   were more 1<>1 with what I'm doing so like:

     Search:
        Search Customizations
        Search Models
        Keyword Based Full Text Search
        Complex Searches
        Geolocation

- [ ] We have a 10.000 limit on results from search, this is OK every one does
    have this starting with google (if you search for something there is never
    "Last Page" button). This is something that is OK but is not explained, and
    it should be.

**Comment by pavelloz** [comment]
Is this actionable?

Some of those are just opinions, some are update requests, some are article requests.

**Comment by diana-lakatos** [comment]
I added these points so that we can discuss, decide what to do and break down into smaller tickets if needed.

**Comment by pavelloz** [comment]
What has been decided?

**Comment by diana-lakatos** [comment]
@Slashek Is there any update related to this issue? Thanks!

**Comment by diana-lakatos** [comment]
User request:

> Any more information you can share?
> We use Elastic Search and also have included Algolia (which sits on top of an in-memory version of Elastic Search)
> If we can do more powerful querying, I'd love to know how.
