### ISSUE TITLE
[BUG] remove reference to marketplace-kit

### ISSUE THREAD

**Issue by lemingos** [Platform-OS/platformos-documentation#714]
https://documentation.platformos.com/how-platformos-works/platformos-workflow/codebase

![Codebase___platformOS_Docs](https://user-images.githubusercontent.com/95296/65785923-cd0a8800-e155-11e9-8117-2ccd52f79d62.jpg)

**Comment by diana-lakatos** [comment]
Thank you for reporting this! Fixed it.
