### ISSUE TITLE
API Reference queries Model Type reference

### ISSUE THREAD

**Issue by digitalfuel** [Platform-OS/platformos-documentation#735]
At this url https://documentation.platformos.com/api-reference/graphql/queries#model Model's `Type` is `customization` which references https://documentation.platformos.com/api-reference/graphql/objects#customization. I think `Type` should be `model` and reference https://documentation.platformos.com/api-reference/graphql/objects#model

**Comment by diana-lakatos** [comment]
Thank you, @digitalfuel! We're looking into this and fixing it.

**Comment by diana-lakatos** [comment]
@Slashek I discussed this with @pavelloz, and we'd need your input on this as well. Thank you!

**Comment by pavelloz** [comment]
Types in graphql are static and we cant change it. Customization = model, but we cant just change it for backwards compatibility
