### ISSUE TITLE
How to disable the instance from indexing by google

### ISSUE THREAD

**Issue by jnorbert** [Platform-OS/platformos-documentation#759]
I noticed that some of the partners asking how it's possible to disable the production instance from indexing by google. Definitely we should inform about it in the documentation. 

From what I know we can do it by using
`<meta name="robots" content="noindex" />`

or

`X-Robots-Tag: noindex`

It will be good to ask eng team what kind of solution it's the best in this case.

**Comment by diana-lakatos** [comment]
@jnorbert Thank you! Is this related to #492?
