### ISSUE TITLE
Update topic: Managing Models using AJAX (CRUD operations)

### ISSUE THREAD

**Issue by diana-lakatos** [Platform-OS/platformos-documentation#782]
Message: The example is wrong. `sort: { name: "created_at", order: "desc" }`  needs to be the following if you are using a custom field outside of pos internal fields. `sort: { properties: { name:"created_at", order:DESC } }`
Feedback to: https://documentation.platformos.com/tutorials/models/crud-models-using-ajax

**Comment by Slashek** [comment]
this has been already solved @diana-lakatos via https://github.com/mdyd-dev/nearme-documentation/pull/781 (thanks @DeanmvSG !!!)
