### ISSUE TITLE
Create example pages and tutorials: PDF generation 

### ISSUE THREAD

**Issue by diana-lakatos** [Platform-OS/platformos-documentation#783]
Discuss how we can leverage this:  https://examples.platform-os.com/pdf-generation to create the Example pages first and then How To step-by-step for our documentation:
1. creating a model, form, page, notification and image upload with uppy
2. creating a model, form, page, notification, async PDF generation

**Comment by Developer-DNM** [comment]
@pavelloz will assist on this :)

**Comment by pavelloz** [comment]
@Slashek will need to describe how it works

**Comment by Developer-DNM** [comment]
:+1:

**Comment by pavelloz** [comment]
> creating a model, form, page, notification and image upload with uppy

https://documentation.platformos.com/developer-guide/models/models-model-schemas
https://documentation.platformos.com/developer-guide/forms/forms
https://documentation.platformos.com/developer-guide/pages/pages
https://documentation.platformos.com/developer-guide/notifications/notifications
https://documentation.platformos.com/developer-guide/user-uploads/uploading-files-directly-amazons3-using-uppy#content

---

To cover: async PDF generation

**Comment by pavelloz** [comment]
Looks like example will be out of date when we roll property_upload

```
mutation generate_pdf($model_id: ID!, $body: String!, $file_name: String!) {
  custom_attachment_create(
    custom_attachment: {
      owner_id: $model_id
      owner_type: "Customization"
      custom_attribute_name: "pdf"
      generate_file: {
        # synchronous: true
        strategy: pdf
        file_name: $file_name
        body: $body
      }
    }
  ) {
    id
  }
}
```

I will wait for working example based on property_upload
