### ISSUE TITLE
Topic missing "last edit" and "contributors" information

### ISSUE THREAD

**Issue by diana-lakatos** [Platform-OS/platformos-documentation#796]
https://documentation.platformos.com/tutorials/properties/arrays
this topic is missing the line below the title that displays the "Last edit:" date and the "Contributors:".

**Comment by pavelloz** [comment]
Its alive!
<img width="642" alt="image" src="https://user-images.githubusercontent.com/546845/69826445-708a1e80-1213-11ea-9bc5-e148fbe4d4b7.png">
