### ISSUE TITLE
Update strip_html output

### ISSUE THREAD

**Issue by diana-lakatos** [Platform-OS/platformos-documentation#799]
Message: strip_html output is wrong in the documentation (in the real world it is fine). 
Feedback to: https://documentation.platformos.com/api-reference/liquid/filters#strip_html

**Comment by pavelloz** [comment]
Turns out its our markdown that is causing this visual bug.

**Comment by diana-lakatos** [comment]
Fixed: https://documentation.platformos.com/api-reference/liquid/filters#strip_html
