### ISSUE TITLE
Add 302 redirects where needed

### ISSUE THREAD

**Issue by diana-lakatos** [Platform-OS/platformos-documentation#815]
When looking for 'related_models' via google search query
https://www.google.com/search?q=site%3Adocumentation.platformos.com+related_models&oq=site%3Adocumentation.platformos.com+related_models

I was pointed to this site: https://documentation.platformos.com/tutorials/model-schemas/loading-related-models

Looks like this is an outdated URL, with model-schemas instead of models (was expecting https://documentation.platformos.com/tutorials/models/loading-related-models ).

It would be great to add appropriate 302 redirects where applicable.

**Comment by hosszukalman** [comment]
The page's new location is here: https://documentation.platformos.com/developer-guide/models/loading-related-models#content
and the correct status could would be `301 Moved Permanently`
