### ISSUE TITLE
Add documentation on the email_send mutation

### ISSUE THREAD

**Issue by diana-lakatos** [Platform-OS/platformos-documentation#824]
User request: 
Add documentation on the email_send mutation, what is the format / keys / values for the data json hashobject? How do you use the template?

**Comment by hosszukalman** [comment]
We also have documentation for `email_send` here: https://documentation.platformos.com/api-reference/graphql/rootmutation.html#L394 and here: https://documentation.platformos.com/developer-guide/notifications/creating-email-notification#step-2a-invoke-notification-directly-via-graphql-email_send
