### ISSUE TITLE
Add to docs: string conversion workaround

### ISSUE THREAD

**Issue by diana-lakatos** [Platform-OS/platformos-documentation#826]
All strings output directly by pos with html in them that are included in markdown `<img> <strong>` etc  (but not `<iframe>` or `<custom>` etc. ) will automatically be converted into "valid" HTML on the server (closing unclosed tags etc)... this is also the case for any code (json / xml) that might contain `<something>` in it (blog for example).
workaround for text and text output:

`{% assign result = text | raw_escape_string %}`
and
`{% print text | raw_escape_string %}`

also when passing json (that contains HTML):

`{%- parse_json json -%} {%- print text | json -%} {%- endparse_json -%}`

**Comment by pavelloz** [comment]
I think we have new way of dealing with it, i forgot what its called or how it looks like

@Slashek
