### ISSUE TITLE
Add information on "dig" filter

### ISSUE THREAD

**Issue by diana-lakatos** [Platform-OS/platformos-documentation#828]
Message: What is the dig filter? What does it do?  {%- graphql g = 'pages_updated_at' \| dig: 'admin_pages', 'results' -%}
Feedback to: https://documentation.platformos.com/api-reference/liquid/platformos-tags

**Comment by pavelloz** [comment]
https://documentation.platformos.com/api-reference/liquid/platformos-filters#dig
