### ISSUE TITLE
Update platformOS tags: add path for module

### ISSUE THREAD

**Issue by diana-lakatos** [Platform-OS/platformos-documentation#829]
Message: query_name - String - name of the GraphQL query. For get_users.graphql file name of the query is get_users  You are assuming /app directory, you need to put a path in for a module
Feedback to: https://documentation.platformos.com/api-reference/liquid/platformos-tags

**Comment by pavelloz** [comment]
https://documentation.platformos.com/tutorials/modules/modules#namespacing-rules
