### ISSUE TITLE
Add more info on "graphql" pOS tag

### ISSUE THREAD

**Issue by diana-lakatos** [Platform-OS/platformos-documentation#830]
**Message:** Pass all arguments at once as a hash: {% parse_json arguments %}   { "model_id": {{ context.params.slug2 \| json }} } {% endparse_json %} {% graphql g = "get_models", args: arguments %}   What does the graphql need to look like? do we still need to list the  queries out one by one or can we just put "args" in the graphql? More  info please.

**Feedback to:** https://documentation.platformos.com/api-reference/liquid/platformos-tags

**Comment by pavelloz** [comment]
@Slashek told you
