### ISSUE TITLE
Remove roadmap pages from search results

### ISSUE THREAD

**Issue by diana-lakatos** [Platform-OS/platformos-documentation#834]
User feedback:
Message: Perhaps remove these from the search, they are just thoughts?
Feedback to: | https://documentation.platformos.com/roadmap/2019-q1/data-import-export-enhancements

**Comment by pavelloz** [comment]
https://github.com/mdyd-dev/nearme-documentation/pull/844 - approve / close depending on decision

**Comment by diana-lakatos** [comment]
Fixed in https://github.com/mdyd-dev/nearme-documentation/pull/848
