### ISSUE TITLE
Update GraphQL queries documentation - feeds

### ISSUE THREAD

**Issue by diana-lakatos** [Platform-OS/platformos-documentation#836]
User feedback: 
Message: There is no information on the arguments for "feeds"
Feedback to: https://documentation.platformos.com/api-reference/graphql/queries

**Comment by pavelloz** [comment]
We might want to switch to a fully SSR generated docs, instead of trying to reimplement it from JSON. Maybe layout/look and feel will be different, but thats expected (and not necessairly bad), as everyone in the biz has it this way.

https://github.com/CodeSignal/graphqldoc

**Comment by pavelloz** [comment]
Examples:
https://2fd.github.io/graphdoc/pokemon/
https://2fd.github.io/graphdoc/shopify/
https://2fd.github.io/graphdoc/github/
https://2fd.github.io/graphdoc/star-wars/

**Comment by pavelloz** [comment]
Old docs dont exist anymore
