### ISSUE TITLE
Extend GraphQL queries documentation

### ISSUE THREAD

**Issue by diana-lakatos** [Platform-OS/platformos-documentation#837]
https://documentation.platformos.com/api-reference/graphql/queries

- [ ] add links to types
- [ ] re-arrange deprecated queries/fields
- [ ] add use cases

Please add any other suggestions for improvements, thank you.

**Comment by Developer-DNM** [comment]
Thanks @diana-lakatos :)

**Comment by pavelloz** [comment]
Ops. I commented in the wrong issue.

My comments should go here:

https://github.com/mdyd-dev/nearme-documentation/issues/836

**Comment by pavelloz** [comment]
https://documentation.platformos.com/api-reference/graphql/graphql

**Comment by pavelloz** [comment]
Old version wont be developed
