### ISSUE TITLE
Add topic: Module Translations

### ISSUE THREAD

**Issue by diana-lakatos** [Platform-OS/platformos-documentation#840]
How to use translation on a module level
- Create your own module translation and how to access it
- Use / Share translation across other modules

**Comment by pavelloz** [comment]
https://documentation.platformos.com/developer-guide/translations/multilanguage-page

This article is about using translations in modules

Whats missing?

**Comment by diana-lakatos** [comment]
I think that the problem might be that users don't find this topic if they look for module translations.  
@Nagygyorgy Did we have any feedback on this during user research? Could we explore this further in future user research sessions?

**Comment by Nagygyorgy** [comment]
@diana-lakatos It didn't emerge in previous research sessions. I add it to my list to discover if it's a problem.
