### ISSUE TITLE
Best practices are very hard to discover

### ISSUE THREAD

**Issue by pavelloz** [Platform-OS/platformos-documentation#842]
This section is very important but if you are not looking actively for the link, its hard to find (footer, homepage).

It depends who we want to cater more, but i would say "how platformOS works" and "getting started" combined take a lot of space in the nav, but dont provide information to users that are already using the platform - best practices has a lot of good information for current users.

**Comment by diana-lakatos** [comment]
Yes, I agree. We were discussing this with @Nagygyorgy, and we are planning to find a solution for it (and also for Use Cases, as that works the same way for now).

**Comment by diana-lakatos** [comment]
Related to #871

**Comment by diana-lakatos** [comment]
Put into main navigation after reorganization: https://documentation.platformos.com
