### ISSUE TITLE
Check and update GraphQL mutation admin_model_schema_create

### ISSUE THREAD

**Issue by diana-lakatos** [Platform-OS/platformos-documentation#847]
User feedback: 
Message: trying to use admin_model_schema_create  "message": "Field 'admin_model_schema_create' doesn't exist on type 'RootQuery'",  Does it not exist anymore?
Feedback to: https://documentation.platformos.com/api-reference/graphql/mutations

**Comment by pavelloz** [comment]
Yes.
<img width="460" alt="image" src="https://user-images.githubusercontent.com/546845/71817404-0bcda980-3086-11ea-97c5-45d1c2b42363.png">


Its mutation not query.

**Comment by hosszukalman** [comment]
I think the documentation is correct. The user only tried to created a query instead of a mutation.
