### ISSUE TITLE
Add topic: Using GraphQL in platformOS

### ISSUE THREAD

**Issue by diana-lakatos** [Platform-OS/platformos-documentation#850]
An introduction article in our tutorials on how to use GraphQL in PlatformOS

- introduction 
- describe {% graphql %} tag
- show an example of a simple query and a simple mutation

**Comment by pavelloz** [comment]
* mention and present in short graphiql

**Comment by diana-lakatos** [comment]
inspiration/re-use content from: https://www.howtographql.com

**Comment by pavelloz** [comment]
This page is more about creating a GQL server (im pretty sure prisma created it, hence everything is done with prisma* tools) which our clients dont have to worry about - we define schema in YML. There is very little we can use from it.

**Comment by pavelloz** [comment]
I think its done: https://documentation.platformos.com/developer-guide/pos-cli/developing-graphql-queries-using-pos-cli-gui
