### ISSUE TITLE
Update Uploading Files Directly to Amazon S3 Using Uppy - content_length

### ISSUE THREAD

**Issue by diana-lakatos** [Platform-OS/platformos-documentation#856]
Update the Uploading Files Directly to Amazon S3 Using Uppy tutorial, Step 2, to include a note about specifying the content_length property, even if just a comment within the mutation example. This is an option that could cause confusion if overlooked.

Notes:
you decide how big/small of a file user can upload during presigning phase
update the content_length lte value for the image_presign_url mutation

**Comment by pavelloz** [comment]
Done https://github.com/mdyd-dev/nearme-documentation/commit/ee3d59710c7fe4ac17fcdc984500a911e005c30a
