### ISSUE TITLE
Add topic: working with date and time in platformOS

### ISSUE THREAD

**Issue by diana-lakatos** [Platform-OS/platformos-documentation#864]
We have: https://documentation.platformos.com/tutorials/translations/date-format 

We should write about filtering by date, checking time offset, formatting date, description of `created_at` and `updated_at` properties, etc.

**Comment by diana-lakatos** [comment]
related to #949

**Comment by pavelloz** [comment]
https://github.com/mdyd-dev/nearme-documentation/issues/562
