### ISSUE TITLE
Reorganize sections and categories

### ISSUE THREAD

**Issue by diana-lakatos** [Platform-OS/platformos-documentation#871]
We are planning to reorganize sections and categories on the documentation site based on external and internal user feedback and user research results.

**Comment by diana-lakatos** [comment]
We could merge the `How platformOS Works` section into the `Tutorials` section (might be renamed later) as follows:

**Tutorials/Basics**
- About platformOS
- Development Workflow (includes current topics Setup, Development Workflow, Partner Portal)
- pos-cli
- Codebase 

TBD: Where to put the Glossary?

**Comment by diana-lakatos** [comment]
After merging the How platformOS Works section into the Tutorials, we could have the following 6 main sections (cards on the home page):

-----------------------
- Get Started
- Tutorials
- API Reference
-----------------------
- Best Practices
- Use Cases
- Community 
-----------------------

**Comment by pavelloz** [comment]
> TBD: Where to put the Glossary?

Might be Getting Started material, at least most of it is recommended before sitting down to coding

**Comment by diana-lakatos** [comment]
Idea TBD: rename Tutorials to Developer Guide 

Now that the Tutorials section will not only contain tutorials but also more concept topics/rules as requested by users, it will become a complete developer guide with the concepts/rules and related tutorials organized into larger sections and categories.  

This would mean that the main part of developer education could be:

- Get Started
- Developer Guide
- API Reference

**Comment by diana-lakatos** [comment]
Reorganization done:
https://documentation.platformos.com

I will open separate ticket for feedback block updates.
