### ISSUE TITLE
Check Uploading Files Directly to Amazon S3 Using Uppy

### ISSUE THREAD

**Issue by diana-lakatos** [Platform-OS/platformos-documentation#884]
Message: I think this src got rendered by liquid or something: `<script src="https://uploads.prod01.oregon.platform-os.com/instances/1/assets/" defer></script>`
Feedback to: https://documentation.platformos.com/tutorials/user-uploads/uploading-files-directly-amazons3-using-uppy

**Comment by pavelloz** [comment]
Fixed https://github.com/mdyd-dev/nearme-documentation/commit/4c651f1aca9cdfc2f89bee4e8aa3655c9292450d
