### ISSUE TITLE
Update GitHub Contributors functionality

### ISSUE THREAD

**Issue by diana-lakatos** [Platform-OS/platformos-documentation#886]
Message from GitHub: 

On February 6th, 2020 at 21:51 (UTC) your application (docs) used its `client_id` and 

`client_secret` (with the User-Agent Ruby) as part of a set of query parameters to access an endpoint through the GitHub API:
https://api.github.com/repositories/131636695/commits
Please use Basic Authentication instead as using OAuth credentials in query parameters has been deprecated.
Depending on your API usage, we'll be sending you this email reminder at most once every 3 days.
Just one URL that was accessed with a User-Agent combination will be listed in the email reminder, not all.
Visit https://developer.github.com/changes/2019-11-05-deprecated-passwords-and-authorizations-api/#authenticating-using-query-parameters for more information.

**Comment by diana-lakatos** [comment]
@Slashek I would like to assign this to @Coornail but I can't. Please advise! Thank you!

**Comment by ignacy** [comment]
This is such a useless feature... I've been saying this for years now: it does not work (related models page does not even show Darek!!) people wasted months on this, and we will still be wasting time on it :/

**Comment by piotrze** [comment]
We don't need this it does not bring any value.

**Comment by pavelloz** [comment]
Nobody wasted months on this ;)
AFAIK nobody touched it from the date it was created by Tomek long time ago.

Having said that, i think feature itself is just a way to test platforms capability to achieve a goal when someone will have a need to do something like this. No matter what value it brings, we still dont know if platform can do such a task reliably.

If you say we waste months on this, and it still doesnt work, and we wrote this, then probably platform has some holes that need to be filled. Would be nice to know what those holes are and fix it before any client will have to go through what we are going through for those months.

PS. This feature might not be useless at all for those who are contributing their time for free to write article to show off their skills and use case. This is the only way to get instant recognition and know that every visitor see their involvement.

**Comment by diana-lakatos** [comment]
@ignacy and @piotrze: This is an important feature, it encourages contribution and provides recognition to partners who contributed like @pavelloz said above. Already now, partners and other external contributors are adding valuable information, fixes and even whole topics, and we would like to have even more community contribution in the future. For partners, this can be a seal of trust and good promotion to show their clients that they are involved and have expertise in platformOS. We also have plans for the future with this feature (e.g. reward the top contributors), so we should find a way to make it work.  

(For now, it worked fine, as long as you don't rename the file.)

**Comment by ignacy** [comment]
@diana-lakatos I cannot find one example of someone outisde of our org that is mentioned there, could you post a link here?

In fact, looking at how this works now, it seems on about 90% of pages we can only see two faces, but those are rarely authors of those features. 

My thinking is: the goal here was to be useful (like the user will know who to ask about given feature) I have a small problem with how the **recognition for contributors** would work.

When a user looks at this it seems very possible they will think: "Oh so I should ask so and so for this topic, he's the author here/domain expert on this". And I think it might be those people will get recognition for building this stuff, and not for what they actully did..
 
Here's an example: on all of the [Models and Model Schemas section](https://documentation.platformos.com/tutorials/models/models-model-schemas) there is no mention of the developer who spend (AFAIK) at least 2.5 years building those things. The knowledge that is used to write those articles, was provided by the author himself, the functionality as well I mean "Contributors" is very misleading in this context.

We could fix this simply by:

* Filtering out from contributors list people from our organization, and making it clear the list is for "people outside of PlatformOS who contributed to this documment"
* Having one page "Contributors" with all the people listed without attaching those to sections, it would be simpler, easier to develop

Just a note here: I would love to be the first one filtered out from contributors list - it does not do anything for me - what bothers me is that those that actually contributed to those things are not mentioned in favour of those who wrote about those things. Seems unfair.

**Comment by diana-lakatos** [comment]
A recent example of a Partner contributor: https://documentation.platformos.com/use-cases/twilio-video-integration

As I was looking for an example of our external contributor on one of the topics, I couldn't find him. If this information got lost somehow, I think we should investigate what the issue was and how we could fix it, regardless of our future plans for this feature. 

If we would like to change this feature, I think we should ask our community about it, and of course examine if our future plans would work with the proposed new solution. 
(cc @Nagygyorgy for potential user research)

**Comment by pavelloz** [comment]
> In fact, looking at how this works now, it seems on about 90% of pages we can only see two faces, but those are rarely authors of those features.

Features? Those are contributors of the docs, which are open source. Unfortunately only two faces contribute to the docs. It would be ideal if feature authors documented their work, but thats not the reality.

When it comes to implementing platform features, those are closed source, and to be honest, people are getting paid to implement them as encouragement to do that.

**Comment by Developer-DNM** [comment]
We 100% need to understand how / why our external contributors aren't being shown in attribution.

It is critical that they are - and with the new Marketing Site about to have a Channel Partner Spot-Light, our recognition and inclusion of Channel Partners and external devs is what will ensure the platformOS ecosystem grows.

It worked with Business Catalyst, Drupal, a myriad of other SaaS / PaaS communities, it'II be vital for pOS success too - we'II work out what's broken here and fix it.

**Comment by Coornail** [comment]
From what I can see now, the issue is that github returns the response for https://developer.github.com/v3/repos/commits/ in paginated form, however, we only process the first page of potentially several. This is why older contributors seem to disappear after a while.

Edit: Unfortunately it is also rate-limited, so fetching all pages is quite complicated.

**Comment by Coornail** [comment]
I had a talk with @Slashek and @diana-lakatos and it seems our repository outgrew the use case where we can reliably get the contributors for each file in an easy way:

We can retrieve a maximum of **30 commits with one request**. We currently have **3440 commits** in our repo (and growing). Github rate-limiting allows **60 requests every 60 minutes**. We have 284 .liquid files under app/views/pages.

As @Slashek suggested, what we could do is to have one page with all our contributors, similarly to the [github readme](https://github.com/mdyd-dev/nearme-documentation#contributors). Here we could manually add contributors as well. We could either remove the _Contributors_ section from our pages, or keep it and rename to _Latest contributors_.

What do you think?

**Comment by Developer-DNM** [comment]
@Coornail let's have a contributor page for now and move on from this.

We can revisit it another time.

Let's wrap this one up asap for now.

**Comment by diana-lakatos** [comment]
We have discussed the next steps with @Nagygyorgy:

- [x] Diana asks Coornail if he can automate
It's automated, first version can be seen here: https://coornail-docu.staging.oregon.platform-os.com/contributors

**Comment by diana-lakatos** [comment]
As the auto-generated page looks decent, we would like to use it as is with minor adjustments (add some copy in the beginning, remove feedback block) and then do the wireframes and design in the next iteration when we do the do new design for the site.

**Comment by pavelloz** [comment]
@Coornail 

You can add &s=X to get proper size of avatar to make it faster.

i.e. https://avatars3.githubusercontent.com/u/30107?v=4&s=120

**Comment by pavelloz** [comment]
Also, hardcoding cdn number would be preferred, to avoid multiple ssl handshakes.
Per https://github.com/mdyd-dev/nearme-documentation/blob/19a0d21f4633156ea44d1501cf401b9d44e8f65f/app/views/partials/layouts/content/contributors.liquid#L41-L42

**Comment by pavelloz** [comment]
Also, `width="120px" height="120px"` s/0px/0 ;)

**Comment by diana-lakatos** [comment]
As discussed with @Nagygyorgy and @Coornail, the task remaining on this ticket are:

- [x] changes based on @pavelloz's feedback
- [x] initial text on top: `Thank you to all our contributors! ` (I will write a different text and insert it once done)
- [x] the contributors page should be accessible here: /community/contributors
- [x] remove the contributor display on topic pages (last edit date should stay)

Thank you!

**Comment by diana-lakatos** [comment]
https://documentation.platformos.com/community/contributors
