### ISSUE TITLE
Add more concept topics/rules to the documentation

### ISSUE THREAD

**Issue by diana-lakatos** [Platform-OS/platformos-documentation#888]
User feedback:
The thing the #documentation lacks probably more than anything else is rules. Lots of tutorials, but I prefer to look up the rules. If I’m looking up `temporary_token`, I want to know what it is, how it is created, how it is invalidated, etc. And then if I want a tutorial, a link to several would be useful.

I’d personally start with the APIs/rules and then introduce tutorials. Seems like that would be more useful. Tutorials are just use-cases. (edited) 

Notes (TBD):
- Concept topics for each category (list)
- Extend existing concept topics 
- Find a place for them during reorganization

**Comment by pavelloz** [comment]
What is call to action to this issue if i wanted to do it?

**Comment by diana-lakatos** [comment]
We have already started doing this with the reorganization and now with the topics we added. Thank you!
