### ISSUE TITLE
Documentation site design update

### ISSUE THREAD

**Issue by diana-lakatos** [Platform-OS/platformos-documentation#894]
Update the design of the documentation site to:

- reflect the platformOS brand and fit into the family of platformOS sites (Partner Portal, marketing site, etc.) 
- address feedback from the community (user research, Slack, etc.)
- address feedback from award judges

**Comment by GyongyGora** [comment]
Based on feedbacks version 1 (attached) will be the new style. Text elements (warnings, link lists, quotes, etc) and sections also got a new style. 

Figma source file and assets: https://www.figma.com/file/jGVHdStunTaBLMWXINGZUK/pOS-docs-design-3?node-id=117%3A2235

![pOS Docs Home v1@2x](https://user-images.githubusercontent.com/57356652/80573054-95bbcc80-89ff-11ea-8c90-569ed2054c8d.jpg)
![Képernyőfotó 2020-04-29 - 9 55 01](https://user-images.githubusercontent.com/57356652/80573070-9ce2da80-89ff-11ea-8ee2-ba01daf5aa99.png)
