### ISSUE TITLE
Add example to strftime filter description

### ISSUE THREAD

**Issue by diana-lakatos** [Platform-OS/platformos-documentation#896]
Looking at these docs: https://documentation.platformos.com/api-reference/liquid/platformos-filters#strftime

It's mentioned that timezone is an optional parameter (as a String), but there is no example and I haven't been able to guess the format- I just get a Liquid error. Please can somebody provide me with an example?

E.g. 
```
{% assign test_time_z = "2021-04-11T00:00:00+01:00" %}
{{test_time_z | json}}<br><br>
{% assign test_time_z = "2021-04-11T00:00:00+01:00" | date: "%s" %}
{{test_time_z | json}}<br><br>
{% assign test_time_z = test_time_z | strftime: '%Y-%m-%dT%H:%M:%S%z', '+01:00'  %}
{{test_time_z | json}}<br><br>
```

**Comment by pavelloz** [comment]
Timezone like UTC, CET, CEST, etc. +01:00 is not a timezone

**Comment by pavelloz** [comment]
AFAIK it needs to be timezone name not offset
IE. UTC, CET

**Comment by diana-lakatos** [comment]
Thank you! Could you please add an example that shows this to the docs?

**Comment by pavelloz** [comment]
Blocked by https://github.com/mdyd-dev/desksnearme/issues/9497
And partly https://github.com/mdyd-dev/desksnearme/issues/9498
