### ISSUE TITLE
GraphQL - Documentation Explorer Issues

### ISSUE THREAD

**Issue by DeanmvSG** [Platform-OS/platformos-documentation#903]
The following descriptions in the Documentation Explorer for GraphQL Mutations are incorrect:

- [ ] `admin_api_call_notification_delete`
- [ ] `admin_api_call_notification_update`
- [ ] `admin_authorization_policy_delete`
- [ ] `admin_authorization_policy_update`
- [ ] `admin_email_notification_delete`
- [ ] `admin_email_notification_update`
- [ ] `admin_liquid_layout_delete`
- [ ] `admin_liquid_layout_update`
- [ ] `admin_liquid_partial_delete`
- [ ] `admin_liquid_partial_update`
- [ ] `admin_model_schema_delete`
- [ ] `admin_model_schema_update`
- [ ] `admin_page_delete`
- [ ] `admin_page_update`
- [ ] `admin_property_delete`
- [ ] `admin_property_update`
- [ ] `admin_sms_notification_delete`
- [ ] `admin_sms_notification_update`
- [ ] `admin_transactable_schema_delete`
- [ ] `admin_transactable_schema_update`
- [ ] `admin_user_profile_schema_delete`
- [x] `admin_user_profile_schema_update`
- [x] `email_send` -> "Email will be queued to send"
- [x] `models_delete_all` -> "comming back" to "coming back"
- [x] `user_profiles_delete_all` -> "comming back" to "coming back"
- [x] `users_delete_all` -> "comming back" to "coming back"

**Comment by diana-lakatos** [comment]
Thank you very much for reporting this in such detail @DeanmvSG.

**Comment by pavelloz** [comment]
All this lies in platform code.
