### ISSUE TITLE
Update documentation: versions_configuration or image_versions

### ISSUE THREAD

**Issue by diana-lakatos** [Platform-OS/platformos-documentation#912]
`versions_configuration` or `image_versions`? Is one of these deprecated? Or do they do separate things?

Task: update documentation to include information to these questions, and more if necessary.

**Comment by pavelloz** [comment]
`versions_configuration` is deprecated
`image_versions` is for images direct s3 upload

**Comment by pavelloz** [comment]
Probably done in https://github.com/mdyd-dev/nearme-documentation/commit/bb4265f64144c1f95cbcc8f49228becff495276f

Only property upload should be used
