### ISSUE TITLE
Prettify direct s3 upload flow diagram

### ISSUE THREAD

**Issue by pavelloz** [Platform-OS/platformos-documentation#930]
@diana-lakatos 

Those flow charts are ugly and show more or less what needs to happen around the browser/app/storage from start to finish (high level) to upload file and save a reference to it in our db.

Some notes:
1) Those lines should be arrows pointing to the next box (in my prototype its always right)
2) Image should be in an aspect ratio that will be fit to our standard documentation layout (ie. https://documentation.platformos.com/developer-guide/user-uploads/uploading-files-directly-amazons3-using-uppy )
This means it probably wont be only left -> right, but it should be obvious that it is ordered - it could be even from top to bottom to make it easy to read
3) Ideally (read: nice to have), SVG format would be the best so that i can edit text if needed and it would look good on highdpi screens
4) Ideally if it were in figma, because next iteration, because this template might be useful for the future (like showing a flow including querying the same data we just uploaded)

Attachments:
![files](https://user-images.githubusercontent.com/546845/75870530-590e9300-5e0b-11ea-90ae-74c0046266f1.png)

Images:
![images](https://user-images.githubusercontent.com/546845/75870532-59a72980-5e0b-11ea-955e-282d7424bea7.png)

Source (in .ai): 
[uploads.ai.zip](https://github.com/mdyd-dev/nearme-documentation/files/4286778/uploads.ai.zip)

**Comment by diana-lakatos** [comment]
Gyöngy is working on this.

**Comment by diana-lakatos** [comment]
@pavelloz I'm sending the svg files on Slack.

Figma source:  https://www.figma.com/file/u4F7QayhXCvV3cC6HczBo7/Illustrations?node-id=15%3A105

**Comment by pavelloz** [comment]
Thank you.

Is there a way to export it from figma as a real svg text tag?
Just like here: https://developer.mozilla.org/en-US/docs/Web/SVG/Element/text
And demo that can be easily edited: https://codepen.io/pen/?&editable=true

This is what i get so far and this means that any change will have to be done in figma, reexported, recompressed.

<img width="601" alt="image" src="https://user-images.githubusercontent.com/546845/76083045-f6ed9380-5fac-11ea-8d1c-51ce754c309a.png">

This is what i searched so far but i still dont know the answer: https://www.figma.com/plugin-docs/api/properties/ExportSettings-svgoutlinetext/

**Comment by pavelloz** [comment]
Ok i figured it out.

For future reference:

<img width="474" alt="image" src="https://user-images.githubusercontent.com/546845/76083306-a0348980-5fad-11ea-90c9-bf1499413900.png">

Outline needs to be unchecked.

Then figma exports broken SVG that you need to fix by replacing any invalid characters, in this case i had to replace `&#3;` to spaces because SVG was invalid otherwise. 

Result is pretty good, image is editable and 23 times smaller: 
<img width="671" alt="image" src="https://user-images.githubusercontent.com/546845/76083418-dbcf5380-5fad-11ea-81d1-b2e930727acc.png">


Unfortunately it looks ugly so ill investigate this some other time.

**Comment by pavelloz** [comment]
Thank you :)
