### ISSUE TITLE
Add file size limit to S3 topics

### ISSUE THREAD

**Issue by diana-lakatos** [Platform-OS/platformos-documentation#943]
User question: 

> Is there an individual file size limit (Staging) when uploading directly to S3?

it's 5GB per file when not multipart
and 5tb for multipart
https://docs.aws.amazon.com/AmazonS3/latest/dev/UploadingObjects.html

downloading - no limits

**Comment by pavelloz** [comment]
add here: https://github.com/mdyd-dev/nearme-documentation/pull/932

**Comment by pavelloz** [comment]
https://github.com/mdyd-dev/nearme-documentation/pull/932/commits/c9831200c634882f27e080bdf370c4dc5577a816 - this should cover it
