### ISSUE TITLE
Add reference of date specifiers

### ISSUE THREAD

**Issue by diana-lakatos** [Platform-OS/platformos-documentation#949]
User feedback: 

If something like this doesn't already exist in the docs (I couldn't find it), I suggest listing out all the available **Date specifiers**. I found the strftime Reference section on this page really helpful... https://help.looker.com/hc/en-us/articles/360023800253-Easy-Date-Formatting-with-Liquid

**Comment by pavelloz** [comment]
What is **date specifier**?

**Comment by diana-lakatos** [comment]
@ScottBReynolds Could you please elaborate on this? Please explain in a bit more detail what you mean or send an example. Thank you!

**Comment by ScottBReynolds** [comment]
**Date specifier** might not be the correct term. I'm requesting something similar to the table under "strftime Reference" (link above) because I wasn't able to correctly format a date in my project with the information available in the pOS documentation.

**Comment by pavelloz** [comment]
What were you formatting from and into?

**Comment by ScottBReynolds** [comment]
From a model's standard "created_at" to a more readable format. The exact output is `"{{ item.created_at | date: "%B %e, %Y" }}"`

**Comment by ScottBReynolds** [comment]
Here's another example (under Date Switches) from Business Catalyst: https://docs.worldsecuresystems.com/reference/liquid/filters.html#date-switches

**Comment by pavelloz** [comment]
So what we should describe?
`%B %e, %Y` those things?

**Comment by ScottBReynolds** [comment]
A table like in either of the examples would work. I recently found a link in the docs that goes to an external site that lists the strftime formats. So maybe that existing link is good enough: https://devhints.io/strftime
