### ISSUE TITLE
Fix typo on GraphQL schema config

### ISSUE THREAD

**Issue by diana-lakatos** [Platform-OS/platformos-documentation#960]
there seems to be a BUG / TYPO on the GraphQL schema config: 
AtachmentInputType => AttachmentInputType 

![slack-imgs](https://user-images.githubusercontent.com/4191691/76836379-06809e00-6831-11ea-879b-668bc7676b3b.png)

**Comment by pavelloz** [comment]
@Slashek 
Worth doing anything considering plans to remove CAs?

**Comment by pavelloz** [comment]
We are removing CA altogether, so not worth investing time into it

**Comment by pavelloz** [comment]
We are removing CA altogether, so not worth investing time into it
