### ISSUE TITLE
Add to Get Started: information about learning curve

### ISSUE THREAD

**Issue by diana-lakatos** [Platform-OS/platformos-documentation#963]
Add some information to the Get Started landing page about the learning curve of platformOS, what the speed of learning depends on (e.g. background knowledge of technologies), plus anything that helps the user understand the learning process.

**Comment by diana-lakatos** [comment]
@Nagygyorgy Do you have information on this topic from user interviews? Thanks!

**Comment by Nagygyorgy** [comment]
@diana-lakatos Yes, we have. Lightbulb and aha moment explains of users explain the learning curve (https://docs.google.com/spreadsheets/d/1oaX7GwUj9e9nZIcGi63lAJCUB9ZPITyLvkdZ_73gwIQ/edit#gid=0) and in the developer experience interview, we gathered some best practices about the tools and solutions (https://docs.google.com/document/d/1AOkDuo37vMHcP9iB8KSzV6HW3EN68Ts_8f_3Je7-bzw/edit?ts=5ea7387e#heading=h.2wi9twaxegd7).

**Comment by diana-lakatos** [comment]
Thank you @Nagygyorgy, this was super helpful! I incorporated the user feedback as tips.
