### ISSUE TITLE
Extend About platformOS

### ISSUE THREAD

**Issue by diana-lakatos** [Platform-OS/platformos-documentation#964]
As it's the first topic in the Developer Guide now, we should explain all major concepts and platformOS' approach. Especially add anything that can help the user get the logic and thinking behind how platformOS works. 
https://documentation.platformos.com/developer-guide/about-platform-os

**Comment by diana-lakatos** [comment]
@Nagygyorgy I'd like to involve you in working on this and use the results of your research where you asked users about their Aha! moments where they understood the logic behind platformOS. Thanks!

**Comment by diana-lakatos** [comment]
Inspiration: https://factor.dev/docs/core-concepts

**Comment by diana-lakatos** [comment]
Task for Liquid section:
- [x] On the Developer guide page, the liquid section should be extended for SEO (+ use "Liquid markup" keywords more) 
https://documentation.platformos.com/developer-guide/about-platformos/about-platformos

**Comment by diana-lakatos** [comment]
Planned structure to write:

About platformOS
- [X] What is platformOS? (current version, might need to be updated)
- [ ] Core Concepts 
- [ ] Reliability 
- [ ] Flexibility 
- [ ] Performance
- [ ] Scalability 
- [X] Security and Disaster Recovery (done)

**Comment by pavelloz** [comment]
Some inspiration: https://www.platformos.com/values
