### ISSUE TITLE
Update instance configuration documentation 

### ISSUE THREAD

**Issue by diana-lakatos** [Platform-OS/platformos-documentation#970]
Update documentation to include the format for the JSON in the configuration section of an instance.

**Comment by hosszukalman** [comment]
I think we already documented this: https://documentation.platformos.com/developer-guide/partner-portal/instances/updating-instance-configuration#content

**Comment by diana-lakatos** [comment]
More information from the user who reported the issue:

https://documentation.platformos.com/developer-guide/partner-portal/instances/updating-instance-configuration#content

> That page is better than it once was but only talks about sections in the JSON. A minimum and a 100% full sample JSON would be great.
> Are we allowed to put custom constants in here? Like am application wide constant? They would be a great idea.
