### ISSUE TITLE
Remove Last edit date from Release Notes pages

### ISSUE THREAD

**Issue by diana-lakatos** [Platform-OS/platformos-documentation#975]
The `Last edit:` date does not need to be displayed on the Release Notes listing page and individual Release Note pages. 

Release Notes listing page:
![Screenshot 2020-03-23 at 15 03 00](https://user-images.githubusercontent.com/4191691/77324678-6981a180-6d17-11ea-9199-aa0e4fa0094d.jpg)

Release Note page: 
![Screenshot 2020-03-23 at 15 03 23](https://user-images.githubusercontent.com/4191691/77324752-84ecac80-6d17-11ea-9a1c-6abfddca3ce5.jpg)

**Comment by pavelloz** [comment]
Fixed
