### ISSUE TITLE
Add opengraph tags

### ISSUE THREAD

**Issue by pavelloz** [Platform-OS/platformos-documentation#984]
To improve visibility

**Comment by pavelloz** [comment]
<img width="1243" alt="image" src="https://user-images.githubusercontent.com/546845/77784668-3282f700-705b-11ea-81f4-4abb20517cb3.png">

Looks better ;)

**Comment by Developer-DNM** [comment]
Cc @arturpawlak @jnorbert please include our go-live checks for SEO and Social Sharing best practices to all the platformOS Marketing pages and Documentation pages.

And I'd like to review the go-live process checklist doc you have, so future client and pOS sites always adhere to them.
And let's share it as a Best Practices How-to on our Documentation site, cc @diana-lakatos

**Comment by jnorbert** [comment]
@Developer-DNM URL to the checklist -> https://docs.google.com/document/d/1D-2jr32SxHvWFDKpC2VqSPOWqiUNWaJEpo_x-I0wrAs/edit?usp=sharing
